library(dplyr)
# df_Pillow <- read.csv("/Users/andreypovaliy/Documents/Science/TKA_quality/archive_01/articles/pillow/data.csv")
df_Pillow <- read.xlsx("df_Pillow.xlsx")
# df_key <- read.csv("/Users/andreypovaliy/Documents/Science/TKA_quality/archive_01/articles/pillow/key.csv")
# 
#   source("func.R")
# source("plots.R")
# setwd("pillow")
# 
# FileName <- "/Users/andreypovaliy/Documents/Science/TKA_quality/text_TKAq.txt"
# df_Pillow <- inner_join(df_Pillow, df_key,by=c("randomisationCode"="key"))
# 
# 
# 
# df_Pillow$group <- factor(df_Pillow$group,
#                           levels = c(1,2),
#                           labels = c("Исследуемая",
#                                      "Контроль")
# )

list_Pillow <- list(compairMain = c("group"),
                         inputData = c("gender", 
                                       "diagnosis",
                                       "bmi",      
                                       "age",           
                                       "heigth",     
                                       "weigth",        
                                       "hka0",        
                                       "deviation",   
                                       "flexPassive0",
                                       "extPassive0",
                                       "romPassive0", 
                                       "flexActive0", 
                                       "extActive0",
                                       "romActive0",
                                       "femurCircum0",
                                       "tibiaCircum0",
                                       "koosP0",
                                       "koosSy0",
                                       "koosA0",    
                                       "koosSp0",   
                                       "koosQ0",   
                                       "koos0"),
                        inputData_transl = c("пол", 
                                      "диагноз",
                                      "ИМТ",      
                                      "возраст",           
                                      "рост",     
                                      "вес",        
                                      "угол механической оси",        
                                      "отколнение",   
                                      "пассивное сгибание до операции",
                                      "пассивное разгибание до операции",
                                      "пассивный объем движений до операции", 
                                      "активное_сгибание_до", 
                                      "активное_разгибание_до",
                                      "активный_объем_движений_до",
                                      "обхват_бедра_до",
                                      "обхват_голени_до",
                                      "анкетирование_боль_до",
                                      "анкетирование_симптомы_до",
                                      "анкетирование_активность_до",    
                                      "анкетирование_повышенная_активность_до",   
                                      "анкетирование_качество_до",   
                                      "анкетирование_общий_балл_до"),
                        inputData_measure = c(" cat", 
                                      " cat",
                                      " кг/м2",      
                                      " лет",           
                                      " см",     
                                      " кг",        
                                      " градусов",        
                                      " cat",   
                                      " градусов",
                                      " градусов",
                                      " градусов", 
                                      " градусов", 
                                      " градусов",
                                      " градусов",
                                      " см",
                                      " см",
                                      " баллов",
                                      " баллов",
                                      " баллов",    
                                      " баллов",   
                                      " баллов",   
                                      " баллов"),
                         outputData = c("surgeon",
                                        "duration",     
                                        "vas1",      
                                        "nsaid1",          
                                        "promedol1",
                                        "hgl2",     
                                        "nsaid2",      
                                        "promedol2", 
                                        "femurCircum3",
                                        "tibiaCircum3",
                                        "flexPassive3",
                                        "extPassive3",
                                        "romPassive3", 
                                        "flexActive3",
                                        "extActive3",
                                        "romActive3",
                                        "vas3",
                                        "nsaid3",
                                        "promedol3",
                                        "hgl12",
                                        "koosP3",
                                        "koosSy3",
                                        "koosA3",
                                        "koosSp3",
                                        "koosQ3",
                                        "koos3"),
                        outputData_transl = c("хирург",
                                       "длительность_операции",     
                                       "ваш_1_день",      
                                       "нпвс_1_день",          
                                       "промедол_1_день",
                                       "гемоглобин_2_день",     
                                       "нпвс_2_день",      
                                       "промедол_2_день", 
                                       "обхват_бедра_3_день",
                                       "обхват_голени_3_день",
                                       "пассивное_сгибание_3_день",
                                       "пассивное_разгибание_3_день",
                                       "пассивный_объем_движений_3_день", 
                                       "активное_сгибание_3_день",
                                       "активное_разгибание_3_день",
                                       "активный_объем_движений_3_день",
                                       "ваш_3_день",
                                       "нпвс_3_день",
                                       "промедол_3_день",
                                       "гемоглобин_12_день",
                                       "анкетирование_боль_3_месяц",
                                       "анкетирование_симптомы_3_месяц",
                                       "анкетирование_активность_3_месяц",
                                       "анкетирование_повышенная_активность_3_месяц",
                                       "анкетирование_качество_3_месяц",
                                       "анкетирование_общий_балл_3_месяц"),
                        outputData_measure = c(" cat",
                                       " минут",     
                                       " баллов",      
                                       " cat",          
                                       " cat",
                                       " г/л",     
                                       " cat",      
                                       " cat", 
                                       " см",
                                       " см",
                                       " градусов",
                                       " градусов",
                                       " градусов", 
                                       " градусов",
                                       " градусов",
                                       " градусов",
                                       " баллов",
                                       " cat",
                                       " cat",
                                       " г/л",
                                       " баллов",
                                       " баллов",
                                       " баллов",
                                       " баллов",
                                       " баллов",
                                       " баллов"),
                         compairSecondary = c("gender","deviation")
)

