---
title: "Retro_group"
author: "К.О. Турбин, Р.А. Ворожбит, А.А. Акулаев, А.А. Повалий"
date: "2023-11-22"
output: html_document
csl: american-medical-association-brackets.csl
bibliography: references_rad.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Введение

Переломы дистального метаэпифиза лучевой кости (ДМЭ ЛК) являются распространенными повреждениями, составляющими от 12% до 17% всех переломов. [@mauck2018evidence; @del2022distal]. Неправильное сращение (НС) ДМЭ ЛК является наиболее распространенным осложнением этой травмы и, следовательно, относительно распространенным клиническим явлением.

Частота НС ДМЭ ЛК, по-видимому, выше, когда перелом лечат гипсовой иммобилизацией, с исторической частотой около 24%. [@katt2020distal; @sharma2014outcomes]. Частота неправильного сращения, ниже при переломах, которые были прооперированы [@sharma2014outcomes]. С появлением передовых хирургических методов частота НС ДМЭ ЛК составила всего 11%. [katt2020distal]. Мета-анализ результатов лечения наружной по сравнению с внутренней фиксацией пластиной показал, что частота НС ДМЭ ЛК составляет около 4% [@wolfe2017distal].

Не все НС ДМЭ ЛК имеют симптомы. Часто степень клинической тяжести не коррелирует с костной деформацией. Тем не менее, при наличии симптомов НС ДМЭ ЛК может привести к значительной инвалидности, и неудачная остеотомия может сохранить или ухудшить статус пациента.

В литературе есть публикации относительно осложнений после корригирующей остеотомии ДМЭ ЛК. Haghverdian и коллеги в 2019 году [@haghverdian2019] сообщили об осложнениях корригирующей остеотомии при внесуставной НС ДМЭ ЛК. Были зарегистрированы инфекция, несращение, потеря репозиции, отторжение импланта, повреждение нерва, повреждение сухожилия и комплексный регионарный болевой синдром, 20% из которых были связаны с сухожилиями. Rivlin и коллеги в 2016 [@rivlin2016] сообщили о 6 пациентах с разрывом разгибателя после остеотомии и фиксации ладонной пластинки для НС ДМЭ ЛК.

Однако помимо осложнений есть еще один важный фактор, который требует изучения – это уровень удовлетворенности и функция после корригирующей остеотомии [@stirling2020patient]. Это фактор достаточно сложно спрогнозировать. Авторы этой статьи поставили целью проанализировать имеющийся опыт операций корригирующей остеотомии и проанализировать связи с функцией.
