---
title: "draft_ch1"
output: word_document
bibliography: references.bib
# csl: gost-r-7-0-5-2008.csl
csl: gost-r-7-0-5-2008-numeric-alphabetical.csl
---

# ГЛАВА №1. СОВРЕМЕННОЕ ЛЕЧЕНИЕ ДЕФОРМАЦИИ ПЕРЕДНЕГО ОТДЕЛА СТОПЫ

## 1.1 Hallux valgus

Hallux valgus представляет собой сложную позиционную деформацию первого луча, которая приводит к изменению механики сустава, дисфункции и прогрессирующей боли, часто в медиальной части первого плюснефалангового сустава (1ПФС) [@ray2019]. Hallux valgus является распространенным заболеванием с предполагаемой распространенностью 23% среди взрослых в возрасте 18-65 лет и 35,7% среди лиц старше 65 лет. В литературе отмечается более высокая распространенность среди женщин с различными соотношениями, варьирующимися от 2:1 до 15:1 на каждого мужчину [@nery2013; @nix2010; @Piqué-Vidal2007].

### 1.1.1 Этиология и патофизиология

Хотя точная биомеханическая этиология hallux valgus не совсем понятна, известно, что медиальная протуберанность или вальгусная деформация стопы является результатом как медиального отклонения первой плюсневой кости, так и латерального отклонения и пронации hallux. Выявлен ряд факторов, создающих предрасположенность к развитию hallux valgus, в том числе женский пол, возраст, стягивающая обувь, генетика [@Coughlin1995; @Coughlin2007; @knörr2022].  Hallux valgus чаще встречается у женщин, что, вероятно, связано с различиями в обуви, костной анатомии, генерализованной слабости связок и гипермобильностью первого луча у женщин [@perera2011]. Стягивающая обувь, такая как высокие каблуки, считается внешним предрасполагающим фактором для hallux valgus из-за повышенной нагрузки на первую плюсневую кость и вальгусного напряжения в плюснефаланговом суставе (ПФС)[^1], когда стопа соскальзывает вперед в узкий носок во время ходьбы [@smyth2018; @menz2016; @munteanu2017]. Распространенность hallux valgus увеличивается с возрастом из-за изменений в механике суставов и подошвенных нагрузках, которые происходят с возрастом [@cai2023] Hallux valgus также, по-видимому, имеет сильную генетическую предрасположенность. В крупном исследовании IV уровня у 90% пациентов с hallux valgus был по крайней мере 1 член семьи с аналогичным заболеванием (n = 350). Хотя точный характер наследования остается неясным, предполагается, что наследование является аутосомно-доминантным с неполной пенетрантностью [@Piqué-Vidal2007]. Другие потенциальные предрасполагающие факторы для hallux valgus включают приведение плюсны, гипермобильность первого луча, плоскую стопу, эквинусную контрактуру, дряблость связок и длину первой плюсневой кости [@al-mohrej2023].

[^1]: плюснефаланговом суставе (ПФС)

Первый луч по своей природе нестабилен, потому что его стабильность зависит от нескольких статических и динамических структур в первом плюснефаланговом (1ПФС) и первом тарсотатарзальном (1ПКС) суставах. Считается, что первой стадией вальгусной деформации hallux является ослабление медиальных опорных структур первого луча, что приводит к медиальному отклонению первой плюсневой кости и латеральному отклонению и пронации hallux, что приводит к прогрессирующей варусной деформации в первом суставе TMT. По мере того, как головка плюсневой кости дрейфует медиально и вращается (во фронтальной плоскости), ее положение по отношению к сесамовидному аппарату изменяется. В результате головка первой плюсневой кости теперь опирается на медиальный сесамовид, в то время как латеральный сесамоид покоится в первом межплюсневом (ИМ) пространстве. Кроме того, деформация в суставе ПФС впоследствии позволяет сухожилиям сгибателя и разгибателя галлюкса сгибаться латерально, оказывая дополнительную деформирующую силу, в то время как смещенный отводящий подошвенный сустав сгибается и пронационирует фалангу. Медиальная протуберанность в первом суставе ПФС обусловлена повышенной заметностью головки первой плюсневой кости [@Steadman2021; @LaPorta2016].

### 1.1.2 Клиническая картина

Первым шагом является запись симптомов пациента. В частности, жалобы и ограничения в повседневной жизни пациента следует отличать от эстетической составляющей. Чисто или преимущественно косметические процедуры не должны проводиться не только из-за возможных осложнений, но и ввиду возможной неудовлетворенности преимущественно бессимптомного пациента болью, связанной с операцией, и трудоемким этапом последующего лечения. Боль, вызванная вальгусной деформацией первого пальца стопы, в основном вызвана 3 патологиями: Основной причиной обычно является псевдоэкзостоз. Это приводит к образованию болезненной бурсы с пролежнями в обуви при запущенной патологии. Кроме того, у пациентов могут развиться жалобы на мизинцы ног из-за смещения большого пальца ноги: образование молоткообразного и когтистого пальцев стопы, развитие второго протока пальцев и переносная метатарзалгия. Если рассматривается хирургическое вмешательство для коррекции hallux valgus, следует задаться вопросом о таких заболеваниях, как сахарный диабет, сосудистые заболевания, атлетическая стопа, нейрогенные заболевания и заболевания ревматического типа. Существующие дегенеративные повреждения суставов должны быть включены в план лечения, как и патологии заднего отдела стопы. Требования и стрессы пациента на работе и в свободное время имеют важное значение для принятия решения о лечении. Кроме того, решающее значение имеет возможная коррекция послеоперационной нагрузки пациента.

### 1.1.3 Методы диагностики

#### **Физикальное обследование**

Медицинский осмотр включает в себя тщательную оценку стопы как в сидячем, так и в стоячем положении. Стопа должна быть осмотрена на предмет любых изменений кожи или повреждений, изменений ногтей на ногах и общего положения первого луча. Определите конкретную локализацию боли на основе анамнеза и пальпации стопы. Боль в медиальной области возвышения типична для пациентов с hallux valgus. Пациенты также могут сообщать о генерализованной боли в первом суставе ПФС, боли, связанной с меньшими деформациями пальцев стопы, или боли в головках малых плюсневых костей из-за переносной метатарзалгии [@dayton2014]. Тщательное нейроваскулярное обследование важно для исключения нейрососудистой недостаточности. Первый луч должен быть оценен на предмет амплитуды движений, слабости связок или контрактур, а также пассивной коррекции деформации, включая внутреннее вращение hallux для оценки редукции первого луча во фронтальной плоскости. Первый сустав ПФС должен быть полностью обследован на предмет любых изменений кожи, боли, крепитации или снижения подвижности, характерных для артритных изменений. Важно оценить наличие любых других сопутствующих процессов, включая деформацию молоткообразного пальца ноги, плоскую стопу, эквинус ахиллова комплекса или гипермобильность первого луча [@ray2019].

#### **Инструментальное обследование**

Основным инструмнтальным методом при HV явялется рентгенологический метод. В рентгенологической оценке HV происходит постепенная эволюция от чисто двумерной интерпретации к анализу деформации в трех измерениях. Это изменение в более полном описании планарных компонентов деформации HV начинает обеспечивать лучшее понимание анатомии стопы и патологической деформации. Несмотря на развивающееся понимание положения в трехмерном пространстве и кинематических отношений, преобладающим средством оценки HV является рентгенологическое изображение в дорсоплантарной проекции. Измерения в двумерной плоскости является наиболее используемыми и они являются основным способом определения тяжести деформации.

##### **Двухмерные оценки**

Оценка hallux valgus на протяжении всего XX века основывалась в основном на плоских угловых соотношениях первого пальца, первой плюсневой кости, второй плюсневой кости и, в меньшей степени, клиновидной кости и проксимальных структур. Используя этот традиционный подход, степень тяжести связывается с величиной угловых измерений. Несмотря на универсальность проведения этих измерений, среди хирургов нет единого мнения относительно наилучшей процедуры для оптимальной коррекции на основе рентгенографических алгоритмов [@hatch2017]. Интересно отметить, что, несмотря на большое разнообразие рекомендаций по определению нормальных и аномальных и предложений по выбору процедуры, большинство этих рентгенографических измерений в поперечной плоскости не были валидированы. Еще LaPorta и коллеги [@laporta1974] в своей работе обсуждали аспекты первого межплюсневого угла (1 IMA)[^2], угла hallux valgus (HVA)[^3], дистального суставного угла (DASA)[^4], proximal articular set angle (PASA)[^5], угол межфаланговой вальгусной деформации (HVIPA) [^6], положение сесамовидной костей и конгруэнтность суставов.

[^2]: 1 IMA - 1 intermetatarsal angle (первый межплюсневый угол)

[^3]: HVA - hallux valgus angle (угол hallux valgus)

[^4]: DASA - distal articular set angle (дистальный суставной угол)

[^5]: PASA - proximal articular set angle (проксимальный суставной угол)

[^6]: HVIPA - hallux valgus interphalangeal angle (угол межфаланговой вальгусной деформации)

Bryant et al. [@bryant2000] также пришли к выводу, что HV ассоциирован с увеличением приведения 1ой плюсневой кости, увеличением ширины раскрютия стопы или 1-5 межплюсневого угла. Condon et al. в 2002 году [@condon2002] описали классические соображения HV, ссылаясь на IMA как нормальный (\<9°), легка деформация (9–11°), умеренныая деформация (11–16°) и тяжелая (\>16°). В зависимости от степени тяжести угла могут быть рекомендованы различные хирургические вмешательства из дистального отдела первой плюсневой кости, дифиза плюсневой кости и проксимального отдела первой плюсневой кости. Подобные наблюдения неоднократно публиковались в классических учебниках по лечению HV [@galois2018; @santrock2018]. Рекомендации приобрели атмосферу правды благодаря повторению и повторной публикации. Угловые соотношения дорсоплантарных рентгенограмм почти повсеместно признаются в хирургии стопы и голеностопного сустава, несмотря на отсутствие доказательств, подтверждающих их роль в определении деформации и выборе процедуры.

Дистальный суставной угол плюсневой кости (DMAA) или проксимальный суставной угол (PASA) обычно обсуждается в связи с HV. Появляется все больше данных, свидетельствующих о том, что это измерение может быть рентгенографическим артефактом, а не истинной деформацией дистальной плюсневой поверхности. Coughlin и Freund [@fraissler2016treatment] проанализировали внутринаблюдательную и межнаблюдательную надежность рентгенологических оценок HV. Их исследование подтвердило надежность вальгусального угла и 1–2 плюсневых углов; однако они поставили под сомнение надежность дистального плюсневого угла (DMAA). В обзоре литературы Coughlin and Jones были обнаружены общие рентгенологические данные при HVA, 1–2 IMA и сезамоидальный подвывих [@coughlin2007hallux]. Позже это было подтверждено Lee et al. в 2012 году [@lee2012reliability], которые пришли к выводу, что вальгусный угол HVA имеет самую высокую надежность, а DMAA — самую низкую среди интраобсерверной и внутринаблюдательной надежности. Тем не менее, они заметили, что DMAA действительно коррелирует с углом вращения сесамовидной формы. Coughlin и Carlson [@doty2015] описали угловые остеотомии при HV, связанные с увеличением 1–2 IMA, дистального угла плюсневой кости и проксимального суставного угла фаланги. Иногда она включала в себя «тройную» остеотомию первого основания плюсневой кости, головки первой плюсневой кости и проксимальной фаланги.

Richardson et al. [@richardson1993first; @fraissler2016] описали DMAA или PASA анатомически и то, как она изменяется в зависимости от деформаций HV. Vittletoe et al. [15] заявили, что измерение DMAA было ненадежным. В 1993 году Мартин [@hatch2017] обнаружил, что предоперационные наблюдения PASA редко коррелируют с интраоперационными данными. В 2002 году Chi et al. [@hatch2017] поставили под сомнение актуальность DMAA и предположили, что вращение первой плюневой кости может влиять на измерение. Robison et al. [@robinson2006] обнаружили, что линейная корреляция DMAA коррелирует с величиной вращения фронтальной плоскости первой плюсневой кости. Дейтон и др. [@dayton2013] обнаружили, что снижение PASA на 18,7° происходило после выполнения артродезирования предплюсневой поверхности с коррекцией во фронтальной плоскости, что также коррелировало измеренные изменения PASA с вращением во фронтальной плоскости. Jastifer et al. [@jastifer2014] сравнили рентгенографическую DMAA с анатомической и обнаружили корреляцию только в 66%. Они считали, что это важный фактор, так как он коррелирует с тяжестью вальгусной деформации. В качестве уточнения терминологии, следует отметить, что дистальный плюсневый угол (DMAA) и проксимальный угол суставного аппарата (PASA) действительно являются одним и тем же измерением и используются взаимозаменяемо для определения угла суставной поверхности плюсневой кости. Из анализа имеющейся литературы ясно, что надежность и клиническая важность дистального угла плюсневых костей вызывает подозрения. Вероятно, это связано с тем, что рентгенографическая оценка DMAA/PASA является двумерным наблюдением и меняется в зависимости от трехмерного положения первого луча. Кроме того, наличие угловой деформации суставной поверхности лица не было подтверждено интраоперационным наблюдением. Понятие конгруэнтности суставов было определено Пигготом в 1960 году [@hatch2017]. Суставы были классифицированы как конгруэнтные, искривленные или субвывихнутые в зависимости от места пересечения линий сустава от головки первой плюсневой кости и основания проксимальной фаланги. Это было связано с адаптацией суставных поверхностей, которая имеет привлекательность для здравого смысла, но не было показано. Неясно, каково истинное влияние конгруэнтности на деформацию HV, и интересно рассмотреть возможное влияние вращения фронтальной плоскости на это рентгенографическое измерение в поперечной плоскости. Принимая во внимание серьезные вопросы, которые существуют в отношении DMAA/PASA, и изменения, которые наблюдаются при многоплоскостном положении, это часто цитируемое рентгенографическое открытие вполне может быть артефактом, обусловленным планарной ориентацией.

Многие исследователи связывают медиальную клинописную форму с возможной этиологией и прогрессированием приведенной плюсны. В 1960 г. Лапидус [@hatch2017] описал угловое отклонение медиальной клиновидной кости которое было названо «атавистическим». Это обнаружение формы клиновидной кости было связано с возможной причиной развития HV[@hatch2017]. Vyas et al. в 2010 году [@vyas2010] обнаружили, что медиальный клиновидный угол наклона не связан с ювенильной HV. С другой стороны, Бернс и Мехам в 2014 году [@burns2014] указали, что многие теория HV предполагают патологию плюснеклиновидного сустава. Однако не все типы суставов с hallux valgus имели суставы аномальной формы. Это было подтверждено Doty et al. [@doty2014], которые обнаружили, что подвижность в первой плюснеклиновидном сустава не была связана с формой сустава или медиальным углом наклона. Сарагас и Беккер также подтвердили отсутствие связи с первым плюсневым клиновидным углом и HV [@shi2020]. Кроме того, Hatch et al. [@hatch2016] обнаружили обратную зависимость от наклона и тяжести вальгусного сустава и пришли к выводу, что наклон сустава является плохим индикатором деформации HV.

##### **Позиция сесамовидных костей**

Еще одним распространенным рентгенологическим измерением, рекомендуемым для определения стадии деформации HV и выбора корректирующих процедур, является положение сесамовидный в поперечной плоскости большеберцовой кости (TSP)[^7]. Как и другие рассмотренные рентгенологические измерения, данные, описывающие роль положения сесамоида в развитии и коррекции HV, претерпели эволюцию. В то время как большинство авторов утверждают, что сесамовидная перестройка имеет решающее значение для общего успеха восстановления HV, проблема заключалась в понимании механики [@lau2021]. В 1951 году Харди и Клэпхем [@togei2024] описали сесамовидное положение большеберцовой кости от одного до семи, где семь является самой тяжелой деформацией hallux valgus.

[^7]: TSP - tibial sesamoid position

Семипозиционное сесамовидное расположение большеберцовой кости Харди и Клэпхэма на рентгенограмме AP [@togei2024]

Ранние исследования в большей степени сосредоточены на рентгенографическом виде AP. Сарагас и Беккер [@saragas1995] указали, что сесамовидные кости неподвижны, а плюсневая кость является компонентом, который движется с повышенной интенсивностью. Кроме того, Woo et al. в 2015 г. [@woo2015] подтвердили, что латеральный высвобождение сесамовидных мышц при хирургической коррекции hallux abducto valgus сам по себе не влияет на положение сесамовидной мышцы. Geng et al. [@geng2016] отметили, что латеральная сесамовидная кости не изменяет положение относительно второй плюсневой кости, что подтверждает более раннее исследование Сарагаса и Беккера. Meyer [@meyr2014] отметил, что TSP одного не наблюдалось в их «нормальной» популяции, что ставит под сомнение то, что мы определяем как норму в отношении сесамоидной популяции. Основная проблема при оценке TSP заключается в том, действительно ли то, что мы видим на рентгенограмме AP и используемой для определения сесамовидного подвывиха, является точным. Талбот и Зальцман [@talbot1998] заявили, что рентгенологическое изображение AP не коррелирует с осевыми видами. По аналогии с медиальными сесамовидными параметрами наблюдаемого латерального сесамоидного положения также обсуждались [@panchani2016]. Влияние выворота плюсневой кости на воспринимаемый сесамовидный подвывих широко обсуждается в последние несколько лет, и его нельзя сбрасывать со счетов.

Кувано [@kuwano2002] идентифицировал вращение сесамоида на осевых проекциях и описал угол поворота сесамовидной проекции. Дальнейшие исследования прояснили важность вращения плюсневой кости во фронтальной плоскости и последующего вращения сесамовидной кости. Dayton et al. [@dayton2014a] в своем исследовании трупов отметили, что вращение фронтальной плоскости коррелирует с изменениями сесамовидного положения большеберцовой кости (TSP) и угла IM. Это также было подтверждено DiDomenico et al. в 2014 году [@didomenico2014]. Идентификация вращения первой плюсневой кости во фронтальной плоскости восходит к DJ Morton [@hatch2017] и Mizuno et al. [@hatch2017]. Авторы подчеркивают важность получения аксиальных рентгенограмм для оценки вращения сесамоидов [@hatch2017]. Аксиальный вид в сочетании с рентгенографическими изображениями AP и LAT обеспечивает 3D-представление положения первой плюсневой кости и первого луча. Стандартизация этого представления важна, поскольку существует множество переменных. Yildirim et al. [@yildirim2005] проиллюстрировали, что величина тыльного сгибания первого плюсневого сустава может влиять на сесамовидное положение. Они обнаружили, что чем больше тыльное сгибание сустава, тем больше тенденция к уменьшению сесамовидных мышц под головкой плюсневой кости. С этим согласились и другие исследователи, использующие исследования компьютерной томографии (КТ) [@hatch2017]. Исследование Lamo-Espinosa et al. показало, что наилучшим положением для оценки сесамоидов будет нейтральное положение без индуцированного тыльного сгибания с помощью компьютерной томографии. Kim et al. в 2015 г. [@kim2015a] исследовали КТ с полувесовой нагрузкой 19 футов без вальгусной деформации большого пальца и 166 футов с вальгусной деформацией. Они определили вращение плюсневой кости как альфа-угол. Основываясь на полученных результатах, они классифицировали четыре различные группы с сесамоидными позициями hallux valgus. Это включало в себя либо плюс, либо минус вращение первой плюсневой кости (P+, P-) и плюс-минус подвывих сесамоидов (S+ S-). Класс P-S- был обнаружен у 2,4% группы hallux valgus. P− S+ присутствовал в 12,7%. P + S− обнаружено у 25,9%, P + S+ — у 61,4%. Общая пронация была обнаружена у 87,3%, сесамовидный подвывих – у 71,7%. В идеале исследования КТ с нейтральным положением должны быть оценены у всех пациентов с отведением большого пальца пальца ноги. По крайней мере, оценка сесамовидного комплекса должна проводиться с помощью аксиальных (корональных) рентгенологических изображений. Из-за обсуждаемой вариативности в будущем необходимо провести дальнейшую стандартизацию этого метода.

##### **Компьютерная томография с нагрузкой**

Трехмерная компьютерная томография (КТ) была усовершенствована, чтобы обеспечить более глубокое понимание патомеханики hallux valgus. Совсем недавно, с помощью технологических достижений, Collan et al. [@collan2013] сообщили об использовании 3-D КТ с нагрузкой для оценки пациентов с hallux valgus в контрольной группе. Несмотря на то, что это не было статистически значимым, они обнаружили, что величина первого вращения плюсневой кости в группе hallux valgus была отклонена на 8° по сравнению с контрольной группой на 2°. Они обнаружили, что клинопись была повернута в вальгусную в большей степени, чем первая плюсневая кость, хотя они обе были повернуты. Одним из методологических вопросов, который может сбить с толку их выводы, является тот факт, что в то время как сканирование проводилось с учетом веса, пациент находился в стойке на одной ноге, а не в функциональном угле и основании походки. Этот факт изменяет общие кинематические отношения, потому что в стойке на одной ноге конечность, несущая вес, поворачивается наружу, вызывая супинацию стопы. Geng et al. [@geng2015] обнаружили, что медиальная клинопись была более вывернута, чем первая плюсневая кость в группе hallux valgus. Kim et al. в 2015 году [@kim2015a] использовали КТ с полунагрузкой в своем исследовании 19 контрольных ног против 166 футов с hallux valgus. Они обнаружили высокую частоту пронации первой плюсневой кости на уровне 87,3% в группе hallux valgus. Величина пронации составила в среднем 15,8°. Их исследование также подтвердило выводы Smith et al. [@conti2021] относительно количества сесамовидных подвывихов от первых стадий головки плюсневой кости 0–3. Lamo-Espinosa et al. [@lamo-espinosa2016] обнаружили у здоровых пациентов (без деформации HV), что появление сесамоидов на КТ было нулевым в соответствии с классификацией Yildirim et al. [@yildirim2005]. Katsui et al. [@katsui2016] обсуждали прямую корреляцию смещения сезамоидов с увеличением тяжести вальгусных и артритных изменений hallux valgus. Kimura et al. [@kimura2017a] изучали 10 футов с hallux valgus и десять нормальных футов с помощью смоделированной КТ с нагрузкой с использованием трехмерного компьютерного анализа. Они подтвердили выводы Geng et al. о повышенном вальгусном вращении медиальной клинопись у пациентов с hallux valgus. Они также обнаружили, что ладьевидная кость была больше в вальгусном положении, в то время как первая плюсневая кость относительно клинопись была немного перевернута в группе вальгусной кости.

Несомненно, что использование КТ с нагрузкой позволит получить больше информации о HV. Понятно, что на конкретном изображении показан только определенный костный сегмент, а не вся стопа. Когда мы говорим о пронации/эверсии плюсневой кости, это относится к исследуемой области, а не ко всему сегменту или лучу. Необходимо позаботиться о том, чтобы понять, что генезис еще предстоит точно идентифицировать и что вращение сегмента может происходить более проксимально, чем в клинописном сочленении плюсневой кости [@barg2017].

#### **Patient-reported outcome measures (PROMs)**[^8]

[^8]:
    #### **Patient-reported outcome measures (PROMs)**

##### AOFAS

Шкала Американского общества ортопедии стопы и голеностопного сустава (AOFAS) [@sierevelt2017] является одной из наиболее часто используемых для оценки заболеваний стопы и голеностопного сустава [@paget2023]. Она объединяет пять пунктов, сообщаемых пациентами, касающихся боли и функции, с четырьмя пунктами, определяемыми врачом, касающимися функции и выравнивания, по шкале от 0 до -100 баллов [@paget2023].

Шкала была разработанная в 1994 году как стандартизированный инструмент для описания боли, соосности и функции стопы и голеностопного сустава [@cöster2014] . Несмотря на то, что ранее она показала низкую конструктную валидность [@alhadhoud2020] и не является строго PROM, поскольку содержит раздел, заполняемый врачом, она по-прежнему остаётся популярной и сегодня.

##### **VAS-FA**

Визуальная аналоговая шкала стопы и голеностопного сустава (VAS-FA) была разработана для оценки субъективных результатов после операции на стопе и голеностопном суставе [@richter2006]. Он был валидирован как для здоровых людей, так и для пациентов с патологиями стопы и голеностопного сустава [@stüber2011]. VAS-FA состоит из 20 пунктов, выполненных в визуальной аналоговой шкале [@stüber2011]. Известно, что визуальная аналоговая шкала проста в использовании, надежна и была валидирована для оценки боли [8]. Пункты можно разделить на три подшкалы, включая боль, функцию и другие жалобы. Балл может быть рассчитан в случае пропущенных ответов. Инструмент был хорошо принят ортопедическим сообществом стопы и голеностопного сустава и переведен на несколько языков [@nair2015]. Сообщалось, что VAS-FA выгодно отличается от других PROM стопы и голеностопного сустава, таких как шкала функциональных заболеваний нижних конечностей (LEFS), индекс остеоартрита Университета Западного Онтарио и Университета Макмастера (WOMAC) и шкала Американского общества ортопедии стопы и голеностопного сустава (AOFAS) [@saarinen2021]. Несмотря на то, что прибор VAS-FA широко протестирован на предмет его психометрических свойств, минимальное важное изменение (MIC) для VAS-FA до сих пор не было оценено. MIC может быть использован для определения клинически значимых изменений по субъективной оценке, полученной от пациента [@saarinen2021]. Несмотря на то, что статистическая значимость полезна для интерпретации изменений, она тесно связана с размером выборки и не интерпретирует значимые клинические изменения в результатах PROM [@ponkilainen2020]. ВПК может быть внедрен как в клиническую, так и в научную работу. MIC указывает на наименьшее изменение с клиническим значением при оценке исходов или последующем наблюдении. Изменения, превышающие MIC, считаются клинически значимыми, что указывает на значимые изменения в состоянии здоровья пациента. Целью настоящего исследования является оценка МПК VASFA с использованием метода якорного предиктивного моделирования.

##### SEFAS

Самооцениваемая оценка стопы и голеностопного сустава (SEFAS) — это широко используемый показатель PROM для оценки физического состояния пациентов с переломами стопы и голеностопного сустава [@arbab2017]. SEFAS берет свое начало от Oxford-12 Hip Score и был разработан и адаптирован Национальным обществом стопы и голеностопного сустава Новой Зеландии [@garratt2018]. Она была переведена и адаптирована на шведский, норвежский и немецкий языки [@garratt2018]. Шведская версия SEFAS показала хорошую надежность и валидность по сравнению с американской ортопедической оценкой стопы и голеностопного сустава (AOFAS), которая ранее считалась золотым стандартом оценки голеностопного сустава [@cöster2014]. В норвежском исследовании сравнивали SEFAS со шкалой функции нижних конечностей (LEFS) и шкалой голеностопного сустава Олеруда Моландера (OMAS) и сообщили, что SEFAS обладает наилучшей способностью измерять изменения физической функции при освещении пациентов с переломами лодыжки [@garratt2018]. Недавно были разработаны нормативные данные для SEFAS, которые облегчают количественную оценку инвалидности, связанной с переломами голеностопного сустава [@cöster2018].

##### FADI и FAAM

Опросник Foot and Ankle Disability Index (FADI) оценивает функцию стопы и голеностопного сустава и ограничения, связанные с заболеваниями опорно-двигательного аппарата [@martin1999development]. Он состоит из двух разделов: основной раздел (26 пунктов): Разделен на подшкалу «Повседневная деятельность» (22 пункта) и подшкалу «Боль» (4 пункта). Для ответов используется шкала Лайкерта от 0 до 4. Максимальный балл за ежедневные активности составляет 104 балла.

FADI-Sport Section (8 пунктов): Формирует подшкалу спортивных мероприятий, также набрав 0-4 балла за элемент, максимум 32 балла. Кроме того, этот раздел включает в себя две различные оценки:

Текущее функциональное состояние во время занятий спортом (оценка от 0 до 100, где 100 = уровень до травмы, 0 = неспособность выполнять повседневную деятельность).

Текущий уровень функционального состояния (классифицируется как нормальный, почти нормальный, сниженный или значительно сниженный). Измерение способности стопы и голеностопного сустава (FAAM), полученное на основе FADI, является еще одним специфическим для региона инструментом для всесторонней оценки функции стопы и голеностопного сустава при различных заболеваниях [@martin2005]. FAAM состоит из двух шкал:

Повседневная деятельность (21 пункт): Соответствует непосредственно пунктам в подшкале «Повседневная деятельность» FADI. Спортивные мероприятия (8 предметов): Соответствует непосредственно пунктам FADI-Sport.

По сравнению с FADI, FAAM опускает пять пунктов повседневной деятельности: один, касающийся функции сна, и четыре, касающихся боли. Кроме того, FAAM просит пациентов оценить свой текущий уровень функционального состояния во время повседневной деятельности по шкале от 0 до 100 баллов.

### 1.1.4 Основные подходы неоперативного лечения

Проспективных рандомизированных исследований на эту тему практически не существует. Как правило, это симптоматическая терапия для уменьшения боли и функционального улучшения[@peters-dickie2025]. Согласно исследованию Kim et al., физиотерапия, по-видимому, способна улучшить вальгусный угол hallux valgus у ранних форм, а также hallux valgus angle при активной абдукции [@kim2015]. Тем не менее, небольшое количество случаев, молодой возраст коллектива и, прежде всего, короткий период наблюдения следует рассматривать как ограничивающие факторы. Структурные изменения более высокой степени могут быть скорректированы только хирургическим путем. Постоянное улучшение положения большого пальца ноги возможно только на растущем скелете без хирургического вмешательства. Консервативная терапия включает в себя консультации по корректировке нагрузки и выбору обуви. Следует носить обувь на плоской подошве или только туфли на низком каблуке. Обувь должна иметь мягкий верх из кожи и достаточно большой носок. Запас обуви может быть дополнен стельками с ретрокапитальной поддержкой в случае переносной метатарзалгии (вариант лечения, который сейчас обсуждался) и регулировкой обуви с помощью вальца вальца или жесткой пружины в случае болезненного остеоартроза плюснефалангового сустава большого пальца ноги. Рекомендуется специальная физиотерапия с упражнениями на укрепление мышц и растяжку, а также мануальная терапия. В настоящее время у всех на слуху терапия hallux valgus по концепции спиральной динамики. Это трехмерная концепция движения и терапии, инструкция по эксплуатации собственного тела с головы до ног. Основным соображением является повторяющаяся структура спирали в анатомии человека и спиральные движения многих суставов. Концепция применения базируется на 4 этапах: восприятие, мобилизация, укрепление, интеграция в повседневную жизнь [@zirngibl2017]. В настоящее время нет достаточного количества научных исследований, подтверждающих эту концепцию. Местно могут использоваться противовоспалительные мази, а в случае острых жалоб также временно может быть использовано применение нестероидных противовоспалительных препаратов (НПВП). Жалобы на мизинцы можно улучшить, установив подушечки пальцев и расширители для пальцев. В среднесрочной перспективе, однако, существует риск того, что мизинцы ног будут смещены латерально или дорсально или, реже, подошвенно, так как существует дисбаланс сил в пользу большого пальца ноги. Восстановительные ортезы удерживают положение только во время их наложения. В качестве чисто ночных позиционирующих ортезов они используются только в период времени, когда на плюснефаланговый сустав большого пальца ноги не действуют децентрирующие силы.

### 1.1.5 Основные подходы оперативного лечения

Хирургическое вмешательство должно показано для тех людей, которым неоперативное лечение не помогло либо из-за постоянных проблем с износом обуви, либо из-за боли. Появление стопы при отсутствии других симптомов не является показанием к хирургическому вмешательству.

Выбор хирургической процедуры традиционно основывался на тяжести деформации, определенной с помощью HVA и IMA, измеренных на рентгенограмме AP с нагрузкой [@robinson2005; @cho2025].

Существует более 100 процедур для лечения вальгусной деформации большого пальца стопы, чаще всего они включают в себя комбинацию процедур балансировки мягких тканей, костной остеотомии и спондилодеза. Недавний рост использования 3-мерной КТ с нагрузкой привлек внимание к компонентам ротационной и сагиттальной плоскости вальгусной деформации первого пальца стопы и привел к разработке новых хирургических методов, которые учитывают трехмерную природу деформации [@kimura2017; @lai2017].

#### **Операции на мягких тканях**

Модифицированная процедура Макбрайда представляет собой дистальную процедуру мягких тканей, которая в основном используется в качестве дополнения к другим корректирующим операциям hallux valgus, таким как проксимальная остеотомия и операция Лапидуса. Эта процедура включает в себя освобождение приводящего галлюциса и латеральной сесамовидной подвешивающей связки [@choi2016]. Завершение процедуры обычно включает в себя бритье медиального возвышения и пликацию медиальной капсулы. Были описаны два хирургических подхода: один метод с использованием медиального трансартикулярного доступа, а другой — с разрезом в дорсальном первом паберинном пространстве. Наиболее распространенным подходом является через первое дорсальное перепончатое пространство из-за лучшей визуализации и более легкого доступа к латеральным мягким тканям. При умеренных и тяжелых деформациях модифицированный метод Мак-Брайда может быть использован в качестве дополнения к плюсневой остеотомии. Сообщалось о высоких показателях удовлетворенности пациентов и значительном улучшении показателей AOFAS при сочетании модифицированного метода Макбрайда с дистальной шевронной остеотомией [@mcaleer2021]. Тем не менее, модифицированный препарат Макбрайда не следует использовать изолированно для лечения hallux valgus, поскольку данные показывают худшие результаты и высокую частоту рецидивов при использовании изолированно по сравнению с дистальной остеотомией плюсневых костей [@choi2016].

#### **Akin остеотомия**

Остеотомия Акина представляет собой медиальную закрывающую клиновидную остеотомию первого проксимального отдела фаланги. Остеотомия Акина обычно выполняется в качестве дополнения к другим процедурам, таким как дистальная шевронная остеотомия, если угол межфаланговой деформации большого пальца вальгуса (HVI) составляет \>10 градусов [@акулаев2022требуется]. Продольный, медиальный разрез делается вдоль первой проксимальной фаланги, и удаляется небольшой клин кости. Важно сохранить целостность латеральной коры в целости; В противном случае существует риск дестабилизации остеотомии [@douthett2018].

#### **Остеотомия дистальных отделов плюсневых костей**

##### **Дистальная шевронная остеотомия**

Остеотомия дистального отдела шеврона показана при вальгусной деформации большого пальца стопы легкой и средней степени тяжести. Эта процедура выполняется с созданием V-образного разреза в дистальном отделе головки/шейки плюсневой кости с боковым смещением дистального отломка. Преимуществами этой процедуры являются присущая ей стабильность тыльного сгибания и минимальное количество укорочения плюсневых костей. В литературе сообщалось о благоприятных исходах с использованием дистальной шевронной остеотомии, особенно при легкой деформации [@kakwani2021]. Последние данные IV уровня показали улучшение показателей исходов стопы и голеностопного сустава (FAOS) у большой когорты пациентов с легкой и умеренной вальгусной деформацией после остеотомии дистального отдела шеврона (n=250) [@vangroningen2016].

##### **Остеотомия длинной руки с шевроном**

Шевронная остеотомия длинной руки позволяет исправить большие деформации за счет удлинения подошвенной конечности остеотомии [@mahadevan2016]. Концепция состоит в том, чтобы улучшить контакт между дистальным фрагментом и проксимальным фрагментом для повышения стабильности коррекции и обеспечения большей коррекции деформации. Недавнее исследование уровня I сравнило остеотомию длинной руки с остеотомией шарфа и обнаружило, что оба метода имеют сопоставимые результаты в коррекции умеренной и тяжелой вальгусной деформации. Тем не менее, дистальный шеврон длинной руки превосходил остеотомию шарфа по величине коррекции IMA (9,1 против 7,1 градуса, *P* = 0,007) [@mahadevan2016]. Остеотомия дистального отдела длинной руки обычно считается менее технически сложным вариантом при умеренной и тяжелой вальгусной деформации. В настоящее время остеотомия шарфа и остеотомия шеврона длинной руки представляются жизнеспособными вариантами коррекции вальгусной деформации средней и тяжелой степени тяжести.

##### **Бипланарная шевронная остеотомия**

Бипланарная шевронная остеотомия позволяет одновременно скорректировать легкую вальгусную деформацию большого пальца стопы и уменьшить DMAA. Разрезы делаются аналогично стандартной дистальной шевронной остеотомии; Тем не менее, больше кости удаляется из дорсомедиальных и подошвенных медиальных конечностей. Кроме того, иссекается косой медиальный клин. Это позволяет осуществлять латеральную трансляцию головки плюсневой кости, а также восстанавливать конгруэнтность сустава ПФС [@decarvalho2022]. Доказательства в поддержку этой процедуры ограничены, хотя удовлетворенность пациентов и функциональные исходы являются благоприятными [@laffenêtre2023].

#### **Диафизарная остеотомия плюсневых костей**

##### **Остеотомия scarf**

Остеотомия шарфа обычно используется для лечения вальгусной деформации первого полевого пальгуса средней и тяжелой степени. Процедура проводится с 3 отдельными остеотомическими разрезами. Первый разрез предполагает создание продольного, подошвенного наклонного разреза проксимального и дистального дистального диафиза плюсневых костей. Затем шевронная остеотомия выполняется дистально в дорсальной коре и проксимально в подошвенной коре, при этом фрагмент головы транслируется латерально. Хорошие и отличные результаты были продемонстрированы при использовании остеотомии шарфа [@adam2011; @bock2015].  Недавнее исследование IV уровня показало, что в среднем при 10-летнем наблюдении у пациентов, перенесших остеотомию шарфа с латеральным высвобождением, наблюдалось улучшение показателей AOFAS с 57 баллов до операции до 95 баллов после операции (P \< 0,05). Они также показали значительное (P \< 0,05) улучшение HVA, IMA и DMAA; тем не менее, частота рецидивов (HVA \>20 градусов) составила 30% при 10-летнем наблюдении [@bock2015] . Потенциальным недостатком является то, что остеотомия шарфа была описана как технически сложная. Частота осложнений была описана от 6% до 47% [@li2023]. Наиболее распространенным осложнением является бороздка, при котором кора головного мозга вклинивается в губчатую кость, что приводит к поднятию первого луча. Методы потенциального предотвращения впадины включают в себя избегание разреза губчатой кости, использование несжимающего винта, ограничение глубины дистального и проксимального разрезов, а также обеспечение максимально дистального разреза, поскольку метафизарная кость имеет лучшую поддержку [@bock2025].

#### **Проксимальная остеотомия плюсневых костей**

Проксимальная остеотомия плюсневых костей обычно назначается пациентам с умеренной и тяжелой вальгусной деформацией большого пальца стопы. К наиболее распространенным проксимальным остеотомиям относятся проксимальный шеврон, проксимальный открывающийся или закрывающийся клин и проксимальный полумесяц. Дистальная процедура мягких тканей, такая как модифицированная операция Макбрайда, обычно используется в качестве дополнения к проксимальной остеотомии.

##### **Проксимальная шевронная остеотомия**

Эта процедура включает в себя медиальный доступ для создания V-образного разреза в проксимальном отделе плюсневой кости с боковым вращением ствола плюсневой кости. Проксимальный шеврон считается более стабильным по своей природе и менее технически сложным, чем другие проксимальные плюсневые остеотомии [@clemente2022]. Исследование I уровня с участием 75 пациентов с вальгусной деформацией первого пальгуса средней и тяжелой степени, в котором сравнивали остеотомию проксимального клиновидного отверстия с остеотомией проксимального отдела, не выявило существенных различий в рентгенологических исходах или времени операции. Аналогичные клинические исходы в отношении боли, удовлетворенности и функции также были отмечены для обеих процедур. В ходе исследования было установлено, что проксимальная шевронная остеотомия укорачивает первую плюсневую кость, в то время как проксимальная остеотомия клиновидной кости удлиняет первую плюсневую кость [@glazebrook2014].

##### **Проксимальная открывающая или закрывающая клиновидная остеотомия**

Проксимальная клиновидная остеотомия является мощным методом для уменьшения ИМА, а также увеличения длины первой плюсневой кости [@watson2021]. В зависимости от размера клина первая плюсневая кость может быть удлинена на 2-3 мм. Из-за этого удлинения остеотомия открывающегося клина может привести к подтяжке медиальных мягких тканей и предрасполагать к жесткости [@watson2021]. В последнее время внимание сместилось на использование открывающихся клиновых пластин из-за их более низкого профиля [@talamoon2024early]. Проксимальная клиновидная остеотомия утратила популярность в результате опасений по поводу высокой частоты рецидивов, укорочения плюсневых костей, нестабильности остеотомии и дорсального сращения [@santos2024].

##### **Проксимальная серповидная остеотомия**

Эта остеотомия включает в себя создание серповидной кости, разрезанной на 1 см дистальнее первого сустава ТМТ с помощью серповидного пильного диска, а затем дистальный фрагмент поворачивается в сторону и фиксируется винтами, проволокой Киршнера или дорсальными пластинами. Сообщалось о высокой удовлетворенности пациентов и отличных результатах со значительным улучшением HVA и IMA у пациентов с тяжелой hallux valgus [@menz2016; @shibuya2019].Трудности этой процедуры связаны с достижением стабильной фиксации места остеотомии, так как нестабильность может привести к дорсальному нарушению. Исследование I уровня, в котором сравнивали проксимальную серповидную остеотомию с проксимальным шевроном при умеренной и тяжелой hallux valgus, не обнаружило существенных различий в коррекции IMA или функциональных исходах между двумя методами. Более короткое время заживления было отмечено при остеотомии проксимального отдела шеврона. В этом исследовании проксимальная серповидная остеотомия привела к большему укорочению плюсневых костей и большему дорсальному мальчленению [@klugarova2017].

#### **Первый тарсотатарзальный артродез (ТМТ) (модифицированный Lapidus)**

Модифицированная процедура Лапидуса традиционно используется для лечения умеренной и тяжелой вальгусной деформации у пациентов с гипермобильностью первого луча, в дополнение к вальгусной деформации большого пальца стопы с сопутствующим артритом pes planus или первым артритом ТМТ. Эта процедура включает в себя сращение первого сустава ТМТ с угловой коррекцией и обычно сочетается с процедурой дистального отдела мягких тканей. Пациенты обычно остаются без веса в течение нескольких недель, чтобы предотвратить подъем первого луча и несращение, что считается слабым местом процедуры. Недавнее крупное многоцентровое исследование, представившее доказательства III уровня, сравнивающее раннюю нагрузку с отсроченной с модифицированной процедурой Лапидуса, не показало никакой разницы в частоте несращения (*P* = 0,663) [@prissel2016]. Другое исследование уровня IV показало низкую частоту несращения, когда тщательная подготовка суставов и компрессия суставов достигались с помощью жесткой винтовой фиксации [@do2022].

Авторы отдают предпочтение трипланарному артродезу ТМТ (модифицированному Лапидусу) с немедленной нагрузкой при умеренной и тяжелой вальгусной деформации первого пальца с гипермобильностью первого луча. Трипланарный метод использует бипланарное покрытие 90-90 для достижения коррекции деформации на вершине деформации или в центре вращения угла. Коррекция деформации достигается за счет деротации первой плюсневой кости для достижения вращения в нейтральной лобной плоскости, а также коррекции в поперечной и сагиттальной плоскостях. Эта конструкция позволяет физиологической микромотории способствовать заживлению в месте остеотомии [@wildemann2021]. Трипланарный артродез ТМТ направлен на достижение коррекции во всех 3 плоскостях при минимизации резекции кости. В настоящее время проводятся исследования по изучению ранних клинических и рентгенологических исходов у пациентов, получавших лечение с помощью этой техники.

#### **Артродез первого плюснефалангового сустава**

Спондилодез первого плюснефалангового сустава (ПФС)[^9] показан при вальгусной деформации первого пальца стопы у пациентов с дегенеративными изменениями в первом суставе ПФС, а также у пациентов с ревматоидным артритом в рамках реконструкции переднего отдела стопы. Первый спондилодез сустава ПФС также является мощным корректирующим вариантом для пожилых пациентов с hallux valgus или в качестве спасательной процедуры после неудачной предыдущей операции по удалению hallux valgus. 34 Изолированное сращение первого сустава ПФС оказалось способным восстановить нормальные IMA и HVA, поскольку исследование IV уровня показало улучшение HVA от 33,0 до 10,4 градусов (*P* \< 0,001) и IMA от 13,1 до 8,6 градусов (*P* \< 0,001) после операции [@novoshelski2025]. У пациентов пожилого возраста, пациентов с предшествующей неудачной хирургической коррекцией, пациентов с артрозом первого сустава ПФС и некоторых пациентов с ревматоидным заболеванием первое артродезирование сустава ПФС для лечения вальгусной деформации первого пальца стопы приводит к отличным результатам, высоким показателям удовлетворенности и низким рискам рецидива [@koutsouradis2021].

[^9]: первого плюснефалангового сустава (ПФС)

#### **Двойная остеотомия**

При двойной остеотомии используется остеотомия как проксимального, так и дистального отдела плюсневых костей для лечения умеренной и тяжелой вальгусной деформации первого пальца стопы с сопутствующим повышенным DMAA. При использовании этой методики существует значительный риск укорочения первой плюсневой кости, что может привести к переносной метатарзалгии. Аваскулярный некроз (АВН)[^10] головки плюсневой кости также является проблемой при двойной остеотомии. Недавнее исследование III уровня, в котором сравнивали двойную остеотомию с проксимальной шевронной остеотомией у пациентов с hallux valgus с повышенным DMAA, не обнаружило существенной разницы в баллах AOFAS или рентгенологических измерениях между группами. В группе двойной остеотомии наблюдалось большее укорочение первой плюсневой кости и более высокие показатели как переносной метатарзалгии, так и АВН головки плюсневой кости [@park2016; @park2018].

[^10]: Аваскулярный некроз (АВН)

#### **Ротационная остеотомия**

В последнее время внимание уделяется методам, которые учитывают трехмерную природу вальгусной деформации первого пальца стопы, в частности, вращение в лобной плоскости (пронация/супинация). Были описаны различные ротационные остеотомии, в том числе ротационный шарф, Ладлоу и проксимальная клиновидная остеотомия. В недавней серии клинических случаев V уровня описывается новая техника ротационной остеотомии при вальгусной деформации большого пальца стопы [@wagner2017]. Проксимальная ротационная остеотомия плюсневой кости включает в себя одну косую остеотомию через проксимальный отдел плюсневой кости. После того, как коррекция вращения достигнута во фронтальной плоскости, устанавливается винт лага и медиальная фиксирующая пластина для фиксации остеотомии. Ранние клинические и рентгенологические результаты серии из 6 пациентов через 7 месяцев после операции обнадеживают, но для валидации этой методики необходимы более долгосрочные и масштабные исследования [@wagner2017].

#### **Минимально инвазивная хирургия**

Методы чрескожной и минимально инвазивной хирургии (MIS) появились в последнее десятилетие из-за потенциальных преимуществ меньшей травмы мягких тканей, сокращения времени операции и более быстрого восстановления [@oleinik2023]. Чрескожные методы обычно используются у пациентов с легкой вальгусной деформацией большого пальца стопы. Было описано несколько методов, таких как минимально инвазивные процедуры шеврона и Акина, артроскопические методы, техника субкапитальной остеотомии и простая, эффективная, быстрая и недорогая техника (SERI). Методика SERI[^11] предполагает фиксацию остеотомии с помощью проволоки Киршнера [@mcaleer2025; @mazzotti2023]. Несмотря на то, что ранние клинические и рентгенологические результаты при МИС являются многообещающими, большинство исследований имеют низкий уровень доказательности, и необходимы дальнейшие долгосрочные сравнительные исследования.

[^11]: simple, effective, rapid, and inexpensive (простая, эффективная, быстрая и недорогая)

#### **Осложнения**

Существуют многочисленные осложнения, связанные с операцией hallux valgus. Рецидив является наиболее распространенным осложнением, частота которого колеблется от 8% до 78% [@jeuken2016; @ezzatvar2021].Причины являются многофакторными и связаны с незрелостью скелета, повышенным DMAA, гипермобильностью, синдромами гиперслабости, нервно-мышечными состояниями, недостаточной коррекцией, техническими способностями хирурга и несоблюдением требований [@nair2022; @cruz2019]. Аваскулярный некроз (АВН)[^12] является редким, но разрушительным осложнением. АВН связан с остеотомией дистальных отделов плюсневых костей, которые нарушают кровоснабжение головки плюсневой кости. ^26,37^ Считается, что вероятность АВН может быть снижена путем предотвращения разрушения боковых сосудов через второй боковой разрез (используемый для высвобождения приводящего сухожилия) и вместо этого высвобождать боковую капсулу через сам сустав [@trnka2025revision].

[^12]: Аваскулярный некроз (АВН)

Перенос метатарзалгии, чаще всего во вторую плюсневую кость, может быть результатом укорочения плюсневых костей или дорсального мальсюнкирования. Укорочение может произойти при любом типе остеотомии плюсневых костей; тем не менее, остеотомия Митчелла (двойной разрез через шейку плюсневой кости), как правило, связана с наибольшим укорочением, при этом некоторые исследования показывают среднее укорочение на 7 мм [@rushing2024].Остеотомия проксимального отдела серповидного сердца традиционно ассоциируется с дорсальной деформацией, хотя некоторые исследования ставят под сомнение этот исход и связывают его с техникой хирурга, податливостью пациента и потерей фиксации [@zhang2020].Хирурги также должны быть осведомлены об осложнениях hallux varus. Hallux varus встречается относительно редко. Это связано с техническими ошибками, включая чрезмерную резекцию медиального аспекта головки плюсневой кости, чрезмерное уплотнение медиальной капсулы, чрезмерное высвобождение латеральной капсулы, чрезмерную коррекцию первой ИМА и иссечение латерального сесамоида [@izzo2022; @mohan2021].

## 1.2 Остеотомия по методу Scarf и Akin

Высокая частота рецидивов после остеотомии по методу скарф [@bock2015] может быть причиной частого выполнения дополнительной остеотомии по методу Акина [@kaufmann2019]. Тем не менее, выполнение дополнительной остеотомии по методу Акина остается решением хирурга; четкие рекомендации по ее показаниям, однако, до сих пор отсутствуют. Некоторые авторы считают остеотомию по методу Акина обязательной для коррекции вальгусной деформации большого пальца стопы [@kerr2010; @kilmartin2010; @lai2017; @lee2017]. На данный момент лишь в нескольких исследованиях представлены данные о результатах комбинированной остеотомии по методу скарф [@agrawal2015; @kerr2010; @garrido2008]. Остеотомия по методу Акина исправляет деформацию первого луча, тогда как остеотомия по методу скарф исправляет вальгусную деформацию первого пальца только на уровне плюсны. После коррекции вальгусной деформации во многих случаях интраоперационно можно обнаружить межфаланговую вальгусную деформацию первого пальца [@park2011]. Авторы данного исследования объяснили этот вывод недооценкой межфаланговой вальгусной деформации первого пальца на предоперационной рентгенограмме. Гиперпронация фаланг может привести к изменению проекции определенных углов. Для оценки патологии фаланг часто используется межфаланговый угол вальгусной деформации большого пальца (HIA), хотя было показано, что измерение этого угла значительно варьируется [@castillo-lopez2014].

## 1.2 Метатарзалгия переноса

Реконструктивная вальгусная хирургия первого пальца стопы является одной из наиболее распространенных процедур в практике стопы и голеностопного сустава. В некоторых случаях после операции развивается болезненный hallux с неправильным положением. При отсутствии метатарзалгии (или даже при умеренно болезненной метатарзалгии с адекватной параболой плюсневой кости) изменения положения первого луча может быть достаточно для достижения безболезненной передней части стопы. К сожалению, могут развиться и другие осложнения операции hallux valgus [@maceira2014]. К распространенным осложнениям относятся недостаточная коррекция или рецидив, чрезмерная коррекция или варусная деформация большого пальца, укорочение, несращение и неправильное сращение с поднятием (тыльным сгибанием) или с подошвенным сгибанием первой плюсневой кости. Иногда эти осложнения могут протекать бессимптомно, но часто приводят к тому, что первая плюсневая кость не может функционировать должным образом. Если первый луч не может выдержать большую часть веса тела во время второго и третьего колебаний походки (контакт передней части стопы с пальцами ног), может произойти смещение подошвенного давления в сторону меньших плюсневых костей. Ятрогенная метатарзалгия переноса встречается чаще, чем считалось ранее, и заболеваемость, возможно, увеличивается [@besse2017; @chahal2020]. В большинстве случаев дисфункция после неудачной операции hallux valgus является причиной меньшей перегрузки плюсневых костей, но неспособность достичь правильной параболы плюсневой кости или неправильное положение остеотомии меньшей плюсневой кости также могут вызвать метатарзалгию переноса соседних плюсневых костей. От 11% до 20% пациентов развивают трансферную метатарзалгию после остеотомии Митчелла. Рецидив деформации и укорочение первой плюсневой кости являются наиболее распространенными причинами трансферной метатарзалгии [@rouveyrol2021; @rajan2022]. Лечение трансферной метатарзалгии после операции hallux valgus представляет собой сложную задачу для опытного хирурга стопы и голеностопного сустава. Глубокое понимание патомеханики, лежащей в основе неудачного hallux, имеет основополагающее значение для планирования правильного лечения. Подробный анамнез и клиническое обследование вместе с визуальными исследованиями позволят определить, что пошло не так и почему. Если консервативные меры не помогают облегчить боль, может быть показана ревизионная операция. В некоторых случаях можно ожидать успешного результата от ревизии первого луча, но в других случаях может потребоваться хирургическое вмешательство на меньших лучах или на обоих вместе, чтобы получить механически исправную переднюю часть стопы. В данной работе исключено обсуждение других осложнений операции hallux valgus, которые могут вызвать переносную метатарзалгию: гематома, повреждение нерва, сложный регионарный болевой синдром, травма, проблемы с кожей вокруг первого луча, инфекция и тромбофлебит. Обсуждение сосредоточено на вопросах патомеханики, клиническом обследовании, визуализационных исследованиях и консервативном хирургическом лечении первого и малых лучей для лечения метатарзалгии переноса [@stavrakakis2024].

## 1.3 Нормальные значения дуги параболы плюсневой кости у мужчин и женщин

Парабола плюсны была объектом изучения различных авторов [@domínguez-maldonado2014]. Большинство опубликованных исследований значений протрузии плюсны относятся исключительно к соотношению между I и II плюсневыми костями, используя расстояние (выраженное в мм) между касательными к двум головкам плюсневых костей в качестве значения протрузии. К этим работам относятся работы Мортона [@zulkifli2020], Харриса и Бита [@malhotra2016], Харди и Клэпхема [@hardy1951] и Лапорты и др. [@laporta1974], в которых разные авторы приводят различные системы для измерения протрузии I-II плюсневых костей и устанавливают различные значения нормы. Вэлли и Риз [@valley1991] разработали три различные системы измерения для оценки протрузии малых плюсневых костей, хотя ни один из них независимо не добился полного анализа параболы плюсны.

С другой стороны, антропометрические различия, приводимые различными авторами относительно выравнивания нижней конечности, указывают на необходимость сравнения средних значений плюсневой дуги у мужчин и женщин. Значительные различия были обнаружены Стилом [@dewitte2018] в размере таранной и пяточной костей, Смитом [@talia2024] в размере плюсневых костей и пальцев ног, а Феррари и др. [@ferrari2004] в ориентации первого луча в поперечной плоскости. Были описаны различия в функциональности нижних конечностей, зависящие от пола. Некототорые исследователи обнаружили различия в угле походки [@lewis2017; @bruening2015] и даже в давлении на подошву во время ходьбы [@shahabpoor2017; @cleland2023].

Domínguez-Maldonado, G. в 2014 году [@domínguez-maldonado2014] исследовали параболы и применили систему измерения, разработанная Харди и Клэпхэмом для оценки протрузии между первой и второй плюсневыми костями [@hardy1951], была адаптирована для изучения всей параболы плюсневых костей и применена к пяти плюсневым костям 169 нормальных стоп, 72 женских стоп и 97 мужских стоп. Авторы измерили протрузию всех плюсневых костей относительно второй плюсневой кости. Полученные результаты показывают, что у женщин выступ плюсневой кости относительно второй плюсневой кости составляет +1,27% для первой плюсневой кости, -3,36% для третьей плюсневой кости, -8,34% для четвертой плюсневой кости и -15,54% для пятой плюсневой кости. Данные, полученные для мужской параболы плюсневой кости, составили +0,5% для первой плюсневой кости, -3,77 для третьей плюсневой кости, -9,57 для четвертой плюсневой кости и -17,05 для пятой плюсневой кости. Различия между обеими параболами плюсневой кости были значительными.

## 1.4 Консенсус относительно классификации деформации передненго отдела стопы

Анализ классификационных систем оценки тяжести вальгусной деформации первого пальца стопы, используемых в литературе, выявил огромную неоднородность как для IMA, так и для HVA [@spindler2024].

Насколько известно авторам, до сих пор ни одно исследование не изучало различные системы классификации, т. е. пороговые значения, используемые для оценки тяжести вальгусной деформации большого пальца стопы. В текущий систематический обзор были включены только сравнительные исследования клинических исходов. Поскольку выбор хирургической процедуры традиционно основан на степени деформации [@izzo2022, @nunes2023], их классификация имеет высокую релевантность. Текущий систематический обзор выявил значительную гетерогенность по критериям порогового значения для различных степеней в отдельных исследованиях. Например, IMA в 14° может быть классифицирована как легкая, умеренная или тяжелая, в зависимости от цитируемой ссылки. Был представлен обзор различных опубликованных систем классификации и консенсус по данным, выявленным в текущем исследовании. Наиболее цитируемыми системами классификации были системы Coughlin и Mann [@spindler2024] и Robinson и Limbers [@robinson2005]. Coughlin и Mann только что опубликовали 10-й том [@spindler2024]. Интересно, что их классификация, по-видимому, также изменилась с течением времени. Классификация Робинсона и Лимберса также рекомендована в национальных рекомендациях Нидерландов по вальгусной деформации [@spindler2024].

Spindler, F. T. и коллеги в 2024 году сообщили, что используемые в настоящее время системы классификации неоднородны. Поэтому любое межисследовательное сравнение ограничено. Более того, они, вероятно, недооценивают многомерный характер деформации. С появлением новых диагностических инструментов, таких как КТ с нагрузкой, и методов лечения, таких как минимально инвазивная хирургия, необходимо разработать новые классификации [@lee2021]. Но только их стандартизация в литературе позволит проводить адекватное межисследовательное сравнение и, следовательно, обеспечить наивысший уровень доказательности [@spindler2024].

## 1.6 Машинное обучение для точной медицины

Происхождение прецизионной или точной медицины до конца не ясно, отчасти из-за эволюции этого термина с течением времени [@j.schuemie2020]. Тем не менее, одной из первых областей, в которых использовался подход точной медицины для лечения заболеваний человека, была трансфузионная медицина, где открытие групп крови в начале 1900-х годов произвело революцию в переливании крови, позволив сопоставить группы крови донора и реципиента и избежать осложнений, связанных с несоответствием донорской и реципиентной крови [@dance2016; @hodson2016]. С тех пор прецизионная медицина значительно эволюционировала, включив в себя новые подходы к профилактике, диагностике, вмешательству и лечению, которые меняют ландшафт медицины. Многие смертельные заболевания теперь имеют методы точной медицины, которые продлевают жизнь и улучшают качество жизни пациентов, например, генная терапия для младенцев со спинальной мышечной атрофией (СМА) I типа — заболеванием, которое когда-то повсеместно приводило к летальному исходу в возрасте до 2 лет. Дети со СМА I типа, прошедшие лечение генной терапией, теперь живут дольше и имеют гораздо меньше серьезных респираторных осложнений, требующих инвазивной респираторной поддержки, что изменило жизнь этих пациентов и их семей [@singh2017]. Опираясь на свой успех и перспективы на будущее, точная медицина теперь является областью, которая пользуется значительной поддержкой со стороны исследовательских и клинических финансирующих агентств, государственных администраций и населения в целом.

### 1.6.1 Краткое введение в машинное обучение

Рост «интеллектуальных» машин и технологий, известных как искусственный интеллект, когда-то был только фантазией, описанной философами, художниками и писателями-фантастами; однако теперь искусственный интеллект является частью повседневной жизни и краеугольным камнем медицины и исследований [@maceachern2021]. Машинное обучение - это отрасль искусственного интеллекта, где создаются компьютерные модели для выявления и изучения закономерностей в многомерных данных для создания моделей прогнозирования и классификации на основе обучающих данных. Термин «машинное обучение» был впервые популяризирован в 1950-х годах Артуром Сэмюэлем, работающим в IBM. С тех пор машинное обучение значительно развилось [@maceachern2021]. Машинное обучение можно дополнительно подразделить на контролируемое и неконтролируемое обучение [@yeung2023], а также обучение с подкреплением. Модели обучения с подкреплением обучаются на основе прямого вознаграждения и наказания в качестве обратной связи за положительные и отрицательные результаты. Положительная обратная связь (вознаграждение) по сути обучает модель машинного обучения повторять решение в будущем, тогда как отрицательная обратная связь (наказание) обучает модель машинного обучения избегать принятого решения в будущем. В связи с необходимостью прямой обратной связи обучение с подкреплением играет довольно малую роль в подходах прецизионной медицины по сравнению с контролируемыми или неконтролируемыми методами машинного обучения.

Машинное обучение без учителя направлено на выявление закономерностей в немаркированных данных. При этом оно может автоматически идентифицировать кластеры схожих случаев в наборе данных. После того, как идентифицированы различные кластеры, их можно визуализировать или дополнительно проанализировать, например, с использованием стандартной статистики. Методы машинного обучения без учителя могут быть особенно полезны для ответа на такие вопросы, как «Существуют ли разные типы заболеваний?» или «Насколько пациент с заболеванием отличается от здоровых людей?». Популярные модели машинного обучения без учителя включают в себя анализ главных компонентов, метод k-ближайших соседей или вариационные автокодировщики (архитектура глубокого обучения без учителя). В отличие от этого, методы машинного обучения с учителем направлены на выявление закономерностей в многомерных данных на основе маркированных данных (например, здоровые против больных или результаты оценки). Точнее, обучающий набор данных с метками истинности обычно используется для построения модели и оптимизации производительности модели машинного обучения для достижения желаемого результата [@husi2019computational; @zou2018]. Обнаруженные (изученные) закономерности затем можно использовать для классификации новых наборов данных или для построения индивидуальных прогнозов, основанных на данных. Модели классификации машинного обучения используются для классификации наборов данных, в то время как модели регрессии обычно используются для прогнозирования непрерывных оценок результатов. Популярные методы статистического и машинного обучения с учителем включают, например, метод опорных векторов, случайный лес, линейные модели и глубокие нейронные сети. Во многих случаях для обеих задач доступны соответствующие модели машинного обучения (например, метод опорных векторов для классификации и метод опорных векторов для регрессии непрерывных оценок результатов).

Для успешного применения методов машинного обучения необходимо учитывать несколько аспектов. Во-первых, входные данные должны быть высокого качества с низким уровнем артефактов или шума. Во-вторых, и это даже важнее низкого уровня шума, – это корректность меток истинности. Хотя модели машинного обучения способны в некоторой степени работать с зашумленными данными, неверные метки могут значительно снизить производительность модели и не могут быть легко выявлены во время обучения. Корректность меток истинности должна быть обеспечена в процессе курирования данных, например, путем использования корректных диагнозов и диагностических меток. Как правило, ошибки в метках истинности оказывают более существенное негативное влияние на точность моделей машинного обучения по сравнению с другими шумами в данных. В-третьих, как и многие статистические методы, большинство моделей машинного обучения также требуют обучающего набора без пропущенных признаков. Поэтому важно, чтобы обучающий набор был максимально полным. Хотя для заполнения пропущенных данных можно использовать методы аугментации данных, которые варьируются от случайной импутации до более сложных алгоритмов машинного обучения, это обычно не обеспечивает такой же эффективности, как использование полного набора данных для обучения. В-четвертых, как правило, предпочтительны более крупные наборы данных, поскольку это позволяет модели машинного обучения изучать истинные вариации в данных с меньшим риском того, что несколько выбросов негативно повлияют на модель. Однако сбор достаточно больших наборов данных является одним из самых больших препятствий для разработки сложных моделей машинного обучения для подходов прецизионной медицины, особенно в контексте редких заболеваний. В-пятых, в алгоритмах классификации важны как точность, так и достоверность, и, следовательно, модели машинного обучения должны быть оптимизированы с учетом обоих аспектов. Наконец, каждая модель машинного обучения должна быть валидирована перед ее использованием для поддержки компьютерной диагностики или принятия решений о клиническом лечении. Например, модель машинного обучения может быть обучена с использованием наборов данных, содержащих случаи, диагностированные врачом. После этого новые случаи могут быть независимо проанализированы врачом и моделью машинного обучения, чтобы можно было сравнить результаты для валидации модели [@kononenko2001].

В рамках контролируемого обучения существует множество моделей классификации и регрессии, которые могут быть использованы для решения конкретной задачи. Каждая из них имеет свои сильные и слабые стороны при рассмотрении конкретной клинической проблемы. Подробное описание этих методов, включая особенности каждого подтипа машинного обучения, выходит за рамки данного обзора. Заинтересованного читателя можно отослать к учебникам, таким как «Прикладное предиктивное моделирование» [@kuhn2013applied], или к обзорным статьям, включая Angermueller и коллеги в 2016 году [@angermueller2016] , Ching и коллеги в 2018 году [@ching2018], а также к недавно опубликованному учебному пособию для врачей [@lovercio2020].

### 1.6.2 Нейронные сети

История искусственных нейронных сетей восходит к 1943 году, когда Уолтер Питтс и Уоррен Маккалок представили первую компьютерную модель нейрона. Между 1965 и 1971 годами Алексей Ивахненко впервые описал небольшие искусственные нейронные сети, состоящие из восьми слоев с взаимосвязанными искусственными нейронами. Однако обучение этих искусственных нейронных сетей было очень дорогим в вычислительном отношении, учитывая имеющееся в то время оборудование и алгоритмы, и, как следствие, популярность этого типа машинного обучения была ограничена. Следующий прорыв был достигнут в 1980-х годах, когда Джеймс Хопфилд представил первую версию рекуррентной нейронной сети [@hopfield1982; @hopfield1984], а Джеффри Хинтон и его коллеги [@najjar2023] популяризировали обратное распространение для обучения нейронных сетей, что позволило значительно более эффективно обучать сложные искусственные нейронные сети. Однако только в начале 2000-х годов появились новые аппаратные средства, особенно специализированные графические процессоры, и еще более эффективные алгоритмы, которые позволили разрабатывать и обучать искусственные нейронные сети со сложной архитектурой и множеством скрытых слоев, которые вскоре начали превосходить многие «классические» методы машинного обучения, такие как машины опорных векторов и случайные леса.

Было разработано множество различных специализированных архитектур нейронных сетей, и в последнее время модели глубокого машинного обучения превосходят традиционные модели машинного обучения во многих задачах, а во многих даже превосходят людей. Например, рекуррентные нейронные сети, включая глубокое обучение с использованием долговременной кратковременной памяти, используются для обработки последовательных временных рядов данных, в то время как сверточные нейронные сети являются мощными инструментами для решения сложных задач обработки сигналов и изображений, таких как автоматическое стадирование опухолей на основе изображений. Сверточные нейронные сети используют сверточные фильтры на первых уровнях глубокой нейронной сети, которые могут автоматически определять важные временные или пространственные характеристики в наборах данных, таких как данные всего генома или данные трёхмерных изображений. Сверточные фильтры оптимизируются так же, как и веса сети. Таким образом, нет необходимости вручную создавать фильтры извлечения признаков: вместо этого исходный набор данных используется непосредственно в качестве входных данных для глубокой сверточной нейронной сети, и оптимальные временные или пространственные характеристики для решаемой задачи машинного обучения определяются автоматически.

Учитывая их мощь и перспективность, методы глубокого обучения, такие как сверточные нейронные сети, вероятно, будут играть все более важную роль в приложениях прецизионной медицины в будущем.

### 1.6.3 Преимущества и ограничения машинного обучения

Машинное обучение, и в частности искусственные нейронные сети, обладает рядом преимуществ для анализа данных в эпоху прецизионной медицины. Одним из основных преимуществ большинства моделей машинного обучения является отсутствие строгих предположений о распределении данных (например, о нормальном распределении). В связи с этим большинство моделей машинного обучения могут легко комбинировать мультиомные данные, включая двоичные, категориальные, дискретные и непрерывные переменные, без необходимости обширной предварительной обработки данных. Благодаря регуляризации, используемой во многих методах машинного обучения, большинство моделей машинного обучения также сравнительно хорошо справляются с зашумленными данными и большими дисперсиями внутри набора данных, хотя, конечно, всегда предпочтительнее меньший уровень шума. Ещё одним преимуществом моделей машинного обучения является наличие специализированных типов и архитектур, которые можно обучать на небольших наборах данных, особенно тех, в которых количество признаков значительно превышает количество наблюдений. В то же время сложные модели машинного обучения могут выявлять многогранные нелинейные закономерности в обучающих данных, которые могут быть неочевидны для наблюдателей-людей или простых линейных моделей.

С другой стороны, машинное обучение также имеет ограничения. Например, способность выявлять сложные нелинейные закономерности также сопровождается ограниченными возможностями интерпретации по сравнению с простыми линейными моделями. По этой причине модели машинного обучения часто критикуют как «черный ящик». В этом контексте важно гарантировать, что такие модели машинного обучения не переобучаются тренировочным данным, что влечет за собой снижение обобщаемости. Переобучение в этом случае означает, что модель машинного обучения работает значительно лучше на тренировочных данных по сравнению с тестовыми. Другими словами, модель машинного обучения слишком хорошо адаптируется к тренировочным данным. Как правило, чем сложнее машинная модель, тем выше вероятность переобучения. По этой причине глубокие нейронные сети с тысячами и миллионами параметров особенно склонны к переобучению. Аналогичным образом, модели машинного обучения также могут недообучать тренировочные данные, что связано с уменьшением точности как тренировочных, так и тестовых данных [@zou2018]. Чтобы гарантировать, что разработанные модели машинного обучения не переобучаются и не недообучаются данным, для оценки разработанной модели машинного обучения обычно следует использовать полностью независимый набор тестов.

## 1.7 Искусственный интеллект в травматологии и ортопедии

Существуют несколько интересных исследований в области травматологии и ортопедии. Следует сказать, что представленные примеры из разных областей травматологии и ортопедии. Но что их объединяет - это решение конкретной научной задачи с применением методов ИИ .

Например, Thong и коллеги в 2016 году провели оптимизации векторов трехмерной модели позвоночника для автоматического обнаружения подросткового идиопатического сколиоза [@thong2016].

Kruse C. и коллеги в 2017 году провели исследование машинного обучения для прогнозирования перелома бедра. Полученная модель для женщин составила AUC 0,92, что можно оценить как отлично, для мужчин AUC 0,89, что оценивается как хороший результат. Авторы пришли к выводу, что машинное обучение может улучшить прогнозирование переломов бедра, выходя за рамки логистической регрессии с использованием ансамблевых моделей.

Cilla M. в 2018 году [@cilla2017] провели анализ машинного обучения для оптимизации тотального эндопротезирования тазобедренного сустава, а именно применение к имплантату тазобедренного сустава с короткой ножкой. Авторы определили, что общая длина ножки была не единственным параметром, играющим роль в защите от избыточных механических напряжений. Оптимизированный имплантат должен стремиться к уменьшению длины ножки и уменьшению площади поверхности, контактирующей с костью. Два радиуса, которые характеризуют ширину ножки в дистальном поперечном сечении, контактирующем с костью, оказывали меньшее влияние на снижение защиты от механических напряжений.

Olczak J. и коллеги в 2017 [@olczak2017] провели исследования распознавания 256 000 рентгенограмм и добились точности 90 % при определении латеритизации, части тела и вида исследования. Итоговая точность с расчётов отбалансированной точности переломов была оценена в 83%, что можно оценить как хорошо работающую модель.

Chen J.H. и коллеги в 2017 году [@chen2017] определили, как изменение данных в электронных медицинских картах могут повлиять на прогнозирование будущих клинических решений в трематологии и ортопедии. То есть авторы поставили достаточно интересный вопрос об оценке «скорости затухания» значимости источника клинических данных. Авторы пришли к выводу, что модели клинической практики, полученные из данных электронных медицинских карт, могут существенно меняться в разные годы. Золотые стандарты поддержки принятия клинических решений — это неуловимые движущиеся цели, усиливающие потребность в автоматизированных методах, способных адаптироваться к меняющейся информации.

Karnuta J.M. и коллеги в 2019 году [@karnuta2019] изучили наивный алгоритм машинного обучения Байеса с определением точности и выявили оперативность прогнозирования продолжительности пребывания и стоимости эпизода лечения перелома бедра с использованием предоперационных переменных. Эта модель продемонстрировала, что стоимость оказания помощи при переломе бедра зависит в значительной степени от немодифицируемых индивидуальных факторов, специфичных для пациента, что, вероятно, делает комплексную помощь неправдоподобной моделью оплаты при переломах бедра.

Ramkumar P.N. и коллеги в 2019 году [@ramkumar2019] изучили предоперационное прогнозирование показателей ценности и модель оплаты для конкретного пациента при первичном тотальном эндопротезировании тазобедренного сустава, разработав и проверив модели глубокого обучения. Модель продемонстрировала обучение с хорошей надежностью и достоверностью в прогнозировании результатов.

Shah R.F. и коллеги в 2019 году [@shah2019] проводили изменение толщины коленного хряща с использованием нового алгоритма машинного обучения для сегментации хряща на магнитно-резонансных изображениях. Было исследовано 3910 МРТ и модель машинного обучения эффективно использовалась для автоматизации сегментации и измерения толщины хряща. Авторы полагают, что развитие этого направления сможет дать большую детализацию для определения факторов развития дегенерации хрящевой ткани.

Harris A.H.S. и коллеги в 2019 году [@harris2019] использовали методы машинного обучения, чтобы создать точные и простые в использовании модели прогнозирования 30-дневных осложнений и смертности после эндопротезирования коленного или тазобедренного сустава. После проведения внутренней и внешней валидации модели были оценены как умеренно точные прогностические модели.
