@startuml

#PeachPuff: 34 человека с неповрежденной верхней конечностью;
group <b>1. Проведение копьтерной томографии </b>
:проводилось МСКТ верхних конечностей;

end group

group <b>2. Создание виртуальной модели </b>

:на основании DICOM файла КТ пациентов проводилось создание
виртуальной модели коллатералных рук;
:проведение измерений по 7 показателям
(более подробно в разделе  "2.1.5 Регистрируемые данные и класификаторы" );
end group

group <b>3. Проведение анализа </b>

#palegreen: оценка возможности использования ЛН, НЛК, ЛВ контрлатьеральной руки
для протокола трехмерного планирования;
end group

@endumll

