@startuml

#PeachPuff: 15 пациентов с НСП ДМЭ ЛК;
group <b>1. Проведение копьтерной томографии </b>
:проводилось МСКТ верхних конечностей;

end group

group <b>2. Создание виртуальной модели </b>

:на основании DICOM файла КТ пациентов проводилось создание
виртуальной модели коллатералных рук;
:проведение остетомии в виртуальной среде;
#MediumTurquoise: регистрация показателей ЛН, НЛК, ЛВ;
end group

group <b>3. Оперативное вмешательство </b>
: Проведение коррегирующей остетомии 
с использованием шаблона направителя;
: Выполнение рентгенограммы 
прооперированной конечности в 2х проекциях;
#MediumTurquoise: регистрация показателей ЛН, НЛК, ЛВ;
end group

group <b>4. Анализ данных </b>
if (Сравнение показателей) then (виртуальные данные)
#PeachPuff:<b>Измерения:</b>
ЛН, НЛК, ЛВ;

else(фактические данные)
#PeachPuff:<b>Измерения:</b>
ЛН, НЛК, ЛВ;
endif 

#palegreen: оценка точности переноса ЛН, НЛК, ЛВ 
изготовленным шаблоно направителем;
end group

@endumll