@startuml



#PeachPuff: 48 пациентов с НСП ДМЭ ЛК;

: подписание согласия на исследование;

group <b>1. Проспективное клиническое исследование</b>

if (Распределение) then (Группа A)
#PeachPuff:<b>Группа A:</b>
26 пациента;
:сбор предоперационных данных;
:проведение опративного вмешательтва 
по стандартному протоколу;
:регистрация данных анкетирования, инструментальных, 
функциональных и интраоперационыых данных;


else(Группа B)
#PeachPuff:<b>Группа B:</b> 
22 пациента;
:сбор предоперационных данных;
:проведение опративного вмешательтва 
по протоколу трехмерного 
планирования с созданием шаблона направителя;
:регистрация данных анкетирования, инструментальных, 
функциональных и интраоперационыых данных;
endif 
end group

group <b>2. Анализ данных</b>
#palegreen:проведено клиническое сравнения данных
анкетирования, инструментальных, 
функциональных и интраоперационыых данных 2х груп;

end group


@endumll