@startuml

:Ретроспективно сбор данных 46 пациетов
завершенные случаи лечения посттравматической деформации ДМЭ ЛК;

group <b>1. Исследование данных медицинской документации </b>

:сбор данных анамнеза, инструментальные данные
до операции;
end group

group <b>2. Исследование данных медицинской документации, сбор данных от пациента </b>

:сбор данных медицинской документации, а также оценка результатов лечения;
end group

group <b>3. Проведение анализа </b>

:оценка результатов лечения в когорте пациентов, 
а также в подруппах разделенных по принципу
    - по типу труда
    - по типу деформации;
end group

@endumll

