@startuml

group <b>1 Этап исследования (ретроспективное клиническое исследование) </b>

#PeachPuff: <b>Группа R:</b> 
46 пациентов;
#palegreen:проведена проведена ретроспективная оценка результатов лечения
НСП ДМЭ ЛК;
end group

group <b>2 этап исследования (экспериментальное исследование) </b>

#PeachPuff: <b>Группа M:</b> 
34 человека с неповрежденной врхней конечностью;
#palegreen:проведена проведена экспериментальная оценка
возможности использования ЛН, НЛК, ЛВ контрлатьеральной руки
для протокола трехмерного планирования;
end group

group <b>3 этап исследования (клинико-экспериментальное исследование) </b>
:разработан протокол предоперационного планирования 
корригирующей остетомии ДМЭ ЛК
с созданием индивидкального шаблона направитяеля;
#PeachPuff: <b>Группа O:</b> 
15 пациентам проведена корригирующей остетомии ДМЭ ЛК
с использованием индивидкального шаблона направитяеля;
#palegreen:проведена оценка точности переноса  запланнированных данных
ЛН, НЛК, ЛВ 
с данным полученными сразу после опеарции;
end group

group <b>4 этап исследования (клиническое исследование) </b>

if (Распределение в группу B) then (нет)
#PeachPuff:<b>Группа A:</b>
26 пациента 
Традиционный протокол;

else(да)
#PeachPuff:<b>Группа B:</b> 
22 пациента
Протокол 3d планирования 
с проектированием шаблона напрвителя;
endif 
#palegreen:проведено клиническое исследование протокола 
3d планирования 
с проектированием шаблона напрвителя;
end group
@endumll

