@startuml
start
group <b>1 этап.	Обсуждение темы и сроков исполнения  </b>
:Тема: оптимизация лечения пациентов в ранеем послеоперационном периоде\n после первичного эндопротезирования коленного сустава;
:Цель: улучшить лечение пациентов в ранеем послеоперационном периоде\n после первичного эндопротезирования коленного сустава;
#afe3db:Формулирование задач;
end group
group <b>2.	Анкетирование трех групп хирургов  </b>
#afe3db:Задача №1: провести анализ современной литеретуры\n относительно вопроса ведения пациентов в ранеем\n послеоперационном периоде;
:Создание первичного текста галвы №1;
:Публикация: Особенности ранниего\n  послеоперационного периода после ТЭПКС (обзор литрертуры);

:Получение информации для создания приложения;
#PeachPuff:решение задачи №1;
end group
group <b>2.	Этап проектировки  </b>
:Принципиальное определение объема и типов данных;
:Определение стека технллогий;
:Реализация технологии;
:Первичная тестировка;
#PeachPuff:решение задачи №2;
end group

group <b>3.	Этап верификации приложения  </b>
:На основании данных первого этапа определить качество\n
10 травматологов и просим диагноз_тактика_прогноз \n
 группа экспертного мнения;
:Созданная модель проводит прогнозирование;
#PeachPuff:решение задачи №3;
end group

group <b>4.  Клинический этап. Проспективное исследование </b>
if (Распределение в группу) then (А)
:группа основанная с использованием предлагаемого метода;
else(Б)
:Контрольная;


endif
end group
#PeachPuff:решение задачи №4;
#SeaGreen:завершение работы;
stop
@endumll