@startwbs
+ Глава №2
++ 2.1 Общая\n структура
+++ 2.1.1 Критерии\n включения и исключения
++ 2.2 Описание методов
+++ 2.2.1 Методы лучевой диагности\n и оценка референтных значений
+++ 2.2.2 Субъективная оценка качества,\n анкетирование
+++ 2.2.3 Функциональные тесты
+++ 2.2.4 Регистрируемые данные\n и класификаторы
+++ 2.2.5 Оперативная техника
+++ 2.2.6 Послеоперационное ведение
+++ 2.2.7 Описние протокола\n предоперационного планирования
++ 2.3 Характеристика\n выборок по этапам
+++ 2.3.1 Ретроспективная оценка результатов
++++_ Описание кагорты
++++_ Описание подгрупп
+++ 2.3.2 Биллатеральное исследование
+++ 2.3.3 Экспериментальная оценка эффективности
+++ 2.3.4 Проспективная оценка результатов
++++_ Описание кагорты
++++_ Описание подгрупп
++ 2.4 Статистика
 
@endwbs