escribir(paste("### ",s2_2_4,"\n\n"))

escribir(paste(  
  "На первом этапе оценивались данные анамнеза, а именно",
  var_gender,",",
  var_years,",",
  var_age,",",
  var_bmi,",",
  var_side,",",
  var_dominant_hand,",",
  var_damage_dominant_hand,",",
  var_type_deformation,",",
  var_type_action,".",
  "Так же регистрировались и оценивались такие рентгенологичекие показатели как",
  var_ri_mes_d_0,",",
  var_ri_gr_d_0,",",
  var_vt_mes_d_0,",",
  var_vt_gr_d_0,",",
  var_rh_mes_d_0,",",
  var_rh_gr_d_0,",",
  var_ri_mes_n,",",
  var_ri_gr_n,",",
  var_vt_mes_n,",",
  var_vt_gr_n,",",
  var_rh_mes_n,",",
  var_rh_gr_n,".",
  "Критерием оценки результата были анкеты",
  var_dash_12,",",
  var_sf_16_ph_12,",",
  var_sf_16_mh_12,".",
  "Как исход лечения оценивались функциональные тесты",
  var_flex_ext_12,",",
  var_diviation,",",
  var_pron_sup_12,".",
  "Так же в оценке качества были рентгенологические показатели",
  var_ri_mes_d_12,",",
  var_vt_mes_d_12,",",
  var_rh_mes_d_12,",",
  var_ri_gr_d_12,",",
  var_vt_gr_d_12,",",
  var_rh_gr_d_12,".",
  "По выявленным показателям проводилась оценка качества коррегирующей остеотомии ",var_localisation," при НСП ", 
  var_localisation,".\n\n" 
))


escribir(paste(
  "На втором этапе оценивалиь инструментальные данные: ", 
  var_rh,",",
  var_vt,",",
  var_medial_vca,",",
  var_median_vca,",",
  var_lateral_vca,"и расчитывалось",
  var_mean_vcas,".\n\n"
))


escribir(paste(
  "На третьем этапе оценивалиcь следующие данные: ", 
  var_month,",",
  var_gender,",",
  var_age,",",
  var_side,",",
  var_dominant_hand,",",
  var_damage_dominant_hand,",",
  var_type_deformation,",",
  var_ri,",",
  var_ri_grad,",",
  var_vt,",",
  var_vt_grad,",",
  var_rh,", а также",
  var_rh_grad,".\n\n"
))

escribir(paste(
  "На четвертом этапе оценивалиcь следующие данные анамнеза: ",
  var_gender	,",",
  var_age	,",",
  var_bmi	,",",
  var_side	,",",
  var_dominant_hand	,",",
  var_damage_dominant_hand,",",
  var_type_deformation," и ",	
  var_type_action ,".",	
  "Инструментальные данные поврежденной руки до операции: ",
  var_ri_mes_d_0	,",",
  var_ri_gr_d_0	,",",
  var_vt_mes_d_0	,",",
  var_vt_gr_d_0	,",",
  var_rh_mes_d_0	," и ",
  var_rh_gr_d_0	,".",
  "Инструментальные данные неповрежденной руки: ",
  var_ri_mes_n	,",",
  var_ri_gr_n	,",",
  var_vt_mes_n	,",",
  var_vt_gr_n	,",",
  var_rh_mes_n	," и ",
  var_rh_gr_n	,".",
  "Данные анкетирования до операции: ",
  var_dash_0	,",",
  var_sf_16_ph_0	," и ",
  var_sf_16_mh_0	,".",
  "Интраоперационные данные: ",
  var_minutes_1	,",",
  var_rg_quantity	,",",
  var_rg_time	,",",
  var_rg_zv	,",",
  "Данные анкетирования, инструментальные, функциоанальные данные данные после операции: ",
  var_dash_12	,",",
  var_sf_16_ph_12	,",",
  var_sf_16_mh_12	,",",
  var_flex_ext_12	,",",
  var_diviation	,",",
  var_pron_sup_12	,",",
  var_grip_strength_12	,",",
  var_vas_3	,",",
  var_ri_mes_d_12	,",",
  var_vt_mes_d_12	,",",
  var_rh_mes_d_12	,",",
  var_ri_gr_d_12	,",",
  var_vt_gr_d_12	,", а также ",
  var_rh_gr_d_12,".\n\n"))


escribir(paste(
  "В исследовании использовалиь классификаторы: ",
  var_ri_grad,",",
  var_vt_grad,",",
  var_rh_grad,",",
  var_type_deformation,",",
  var_type_action,", а также",
  var_damage_dominant_hand,".",
  "Тип деформации ладонная или дорсальная деформация определялись по показателю",
  var_vt,
  "если меньше референтных значений, то дорсальная, если больше, то ладонная.",
  "Тип труда был ручной, если пациент имел работу и его труд завиел от функции руки",
  "смешанный, если пациент имел или не имел работу и трудоспосоьного возраста",
  "и пенсионер, если пациент был нетрудоспособного возраста",
  "Классификация лучевого наклона определялись по показателю",
  var_ri, 
  ", и относительно рефертного значения опряделось меньше, норма или больше",
  "классификация ладонного наклона определялись по показателю",
  var_vt, 
  ", и относительно рефертного значения опряделось меньше, норма или больше",
  "классификация лучелоктевого индекса определялись по показателю",
  var_rh, 
  ", и относительно рефертного значения опряделось меньше, норма или больше",
  "Повреждение доминирующей руки считалось истинным если сторона поврежденной руки совпадала с доминирующей рукой. ",
  "Все рефернетные зачения можно увидеть в разделе '",
  s2_2_1,
  "'.\n\n"
))
