---
title: "get_bibl"
author: "Andrey_Poavaliy"
date: "2025-06-15"
output: html_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Этот файл нужен для сбора материала и ссылок для обзора литетратуры

## 1.1 Анатомо-физиологические особенности ПКС

### 1.1.1 Анатомпия ПКС

Анатомия передней крестообразной связки и ее значение в реконструкции передней крестообразной связки [@markatos2012]

Артроскопия на современном уровне: анатомия передней крестообразной связки [@schillhammer2016]

### 1.1.2 Биомеханика ПКС

Анатомия передней крестообразной связки и ее значение в реконструкции передней крестообразной связки [@markatos2012]

## 1.2 Клинико-диагностические особенности разрыва ПКС

### 1.2.1 Эпидемология

#### \* Спортивная травма

### 1.2.2 Клиническая картина

### 1.2.3 Физикальные тесты

### 1.2.4 Инструментальные данные

## 1.3 Ключевые факторы успешности реконструкции ПКС

### 1.3.1 Выбор трансплпнтата для реконструкции ПКС

### 1.3.2 Предоперационная оценка толщины трансплантата

### 1.3.3 Ресположение тонелей для трансплантата

### 1.3.4 Выбор способа креплпния

## 1.4 Выбор трансплпнтата для реконструкции ПКС

### 1.4.1 Bone-Patellar Tendon-Bone

### 1.4.2 Hamstring Tendon

### 1.4.3 Single-Bundle Autologous Quadriceps Tendon

### 1.4.4 Peroneus graft

## 1.4 Выбор трансплпнтата для реконструкции ПКС

Сбор аутотрансплантата сухожилия длинной малоберцовой мышцы полной толщины [@franciozi2023]

Извлечение сухожилия длинной малоберцовой мышцы для реконструкции передней крестообразной связки[@butt2022]

Аутотрансплантат сухожилия длинной малоберцовой мышцы: перспективный трансплантат для реконструкции передней крестообразной связк [@budhiparama2021]

## 1.5 Осложнения после забора трансплантата

Осложнения после забора трансплантатов из сухожилия надколенника или подколенного сухожилия для реконструкции передней крестообразной связки: систематический обзор литературы [@hardy2017]

Связь между техникой разреза для забора сухожилия подколенного сухожилия при реконструкции передней крестообразной связки и риском повреждения поднадколенниковой ветви подкожного нерва: метаанализ [@grassi2018]

Реконструкция передней крестообразной связки: систематический обзор и метаанализ результатов аутотрансплантата сухожилия четырехглавой мышцы бедра по сравнению с аутотрансплантатами кость-сухожилие надколенника-кость и подколенное сухожилие-сухожилие [@mouarbes2019]
