@startuml
#FFB6C1:Цель: улучшить результаты лечения пациентов с первичной 
пластикой ПКС;
start
#Orange:1.По данным литературы выявить проблему **забора трансплантатата**, 
а также возможностей предикции **размера трансплантата**;
#lightgreen:Ожидается  выявить: 
    1 - размер Peroneus сложно предсказать,
    2 - ST может быть меньше 8 мм или пограничного значения
    3 - часто выбор трансплантата сопряжен с предпочтениями хирурга
    4 - нет учета антропометрических данных и гендерных различий;
#ADD8E6: Статья №1. Обзор литературы;
#Orange:2.По данным анализа собственого материла ретроспективно оценить результаты 
первичной пластики ПКС;
#lightgreen:Ожидается  выявить: 
    1 - существует проблема забора трансплантата
    2 - выбор трансплантата не оптимален с точки зрения удовлетворенности;
#ADD8E6: Статья №2. Причины неудовлетворенности при правильном выполнении ПКС;
#Orange:3.Разаработать и апробировать новый инструмент для забора трансплантата 
с учетом антропометрических особенностей пациента;
#lightgreen:Ожидается  получить: 
    1 - Создание новго инструпента для забора трансплантата, 
    позволяющий учитывать необходимую длинну
    2 - Выявлена чувствительная группа пациентов для которых использование 
    стандартного инструмента не целесобразно;
#ADD8E6: ПАТЕНТ №1. Телескопический сриппер;
#Orange:4.Предложить метод, позволяющий пердсказывать толщину трансплантата;
#lightgreen:Ожидается  получить: 
    1 - Создание новго метода, позволяющего предсказать размеры трансплантатов и 
    как слесдвеи оптимизировать его выбор на этапе подготовки;
#ADD8E6: Статья №3. Как предсказать размер Peroneus при стандартом МРТ колена;
#Orange:5.На основании полученных данных предложит новый алгоритм выбора и забора трансплантата;
#lightgreen:Ожидается  получить: 
    1 - Сформулированный алгоритм;
#Orange:6.Провести проспективное исседование применения нового алгоритма;
#lightgreen:Ожидается  получить: 
    1 - При сравнении 2х групп выявить улучшения в удовлетворенности в группе, 
    где применен алгоритма;
#ADD8E6: Статья №4. Применение нового алгоритма выбора и забора трансплантата ПКС;
stop
#9ACD32: Достигнута цели исследования и последовательно выполнены все задачи;

@enduml
