---
title: "Chapter_1"
author: "AndreyPovaliy"
date: "2023-09-26"
output: html_document
bibliography: "references1.bib"
csl: "gost-r-7-0-5-2008-numeric-alphabetical.csl"
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **ГЛАВА № 1. Современные методы лечения посттравматической деформации дистального метаэпифиза лучевой кости**

В этой главе будут последовательно рассмотрены темы, позволяющее создать представление о современных подходах к лечению посттравматической деформации дистального метаэпифиза лучевой кости (ДМЭ ЛК)[^1].
Вначале кратко будут рассмотрена анатомия данной области.
Далее будет представлено описание современного состояния проблемы переломов дистального метаэпифиза со способами их оценки.
Затем фокус внимания будет сконцентрирован на проблеме неправильного сращения перелома (НСП[^2]) дистального метаэпифиза лучевой кости, как осложнения лечения перелома в рамках этой темы будет уделено внимания уже осложнениям лечения неправильного сращения перелома
. Также в главе будет представлена информация о компьютерных технологиях, а именно трехмерные технологии проектирования и печати, которые уже применяются в лечении данной патологии как перспективной области
.

[^1]: ДМЭ ЛК - дистальный метаэпифиз лучевой кости

[^2]: НС - неправильное сращение перелома

## **1.1 Особенности анатомии лучезапястного сустава**

Для наиболее лучшего понимания проблемы лечения последствий переломов ДМЭ ЛК следует обратиться к современному понимаю анатомических особенностей области, а именно какие костные структуры участвуют в соединениях и какие связки образуют стабилизацию сегмента [@mauck2018].
Модель трех колон - является базовой концепцией на сегодняшний день для понимания как взаимодействуют анатомические структуры изучаемой анатомической области [@kennedy2013]

### **1.1.1 Остеология**

В дистальном отделе лучевой кости имеются три независимые суставные поверхности: ладьевидная фасетка, полулунная фасетка и сигмовидная выемка лучелоктевого сустава.
Лучезапястное сочленение находится на лучевой стороне дистального отдела предплечья, включая шиловидный отросток лучевой кости.
Лучезапястное сочленение и сигмовидная выемка составляют локтевую часть предплечья.
Сигмовидная выемка ориентирована перпендикулярно полулунной фасетке, образуя дистальный лучелоктевой сустав (ДЛЛС)[^3].
Сигмовидная выемка имеет полуцилиндрическую форму, обеспечивая сочленение дистального отдела локтевой кости и образует ДЛЛС, который облегчает комбинацию движений [@ekenstam1985; @mauck2018].

[^3]: ДЛЛС - дистальный лучелоктевой сустав

Дистальный отдел локтевой кости рассматривается как точка опоры для пронации и супинации запястья, вокруг которой вращаются дистальный отдел лучевой кости и запястье.
Смещение происходит из-за большего радиуса кривизны сигмовидной выемки (неглубокой) и головки локтевого сустава.
Это приводит к дорсальному и ладонному перемещению во время пронации и супинации соответственно [@ekenstam1985].

Существуют различные степени плотности кости в дистальном отделе лучевой кости, и они участвуют в распространении перелома между ладьевидной и полулунной фасетками [@melone1984articular; @melone1986open; @melone1993distal].

### **1.1.2 Синдесмология**

Прочные связочные комплексы обеспечивают необходимую стабилизацию суставов запястья.
Условно связки запястья можно разделить на внешние и внутренние.
Внешние связки соединяют запястные кости с дистальными отделами лучевой кости или пястных костей.
Внутренние связки берут начало и крепятся к костям запястья.
Лучеладьевиднополулунная, лучеладьетрехгранная, лучеладьеголовчатая связка и дорсальная лучеладьевидная связки прикрепляются к суставному краю дистального отдела лучевой кости и соответствующих запястных костей.
Комбинация внутренних и внешних связок служит для формирования стабильных сочленений и направления векторов силы к лучезапястному суставу.
Треугольный фиброзно-хрящевой комплекс (ТФХК[^4]) и его ладонная и тыльная лучелоктевые связки являются основными стабилизаторами сустава [@adams2007; @palmer1981].

[^4]: ТФХК - Треугольный фиброзно-хрящевой комплекс

Прочные связки полулунной фасетки в сочетании с ТФХК играют большую роль в стабилизации локтевого сустава запястья.
Этот исключительно прочный связочный комплекс является причиной того, что запястье практически всегда смещается вместе с фрагментом переломанного дистального отдела лучевой кости [@nana2005].

### **1.1.3 Модель трех колонн**

Rikli D. A.
и Regazzoni P. в 1996 году описали [@rikli1996fractures], дистальные отделы лучевой кости и локтевой кости, лучезапястное сочленение и ДЛЛС можно концептуально анатомически разделить на модель с тремя различными колоннами: лучевая колонна, промежуточная колонна и локтевая колонна [@kennedy2013].

Лучевая колонна и промежуточная колонна поддерживаются "стержнем", образованным метадиафизарной дистальной частью лучевой кости.
Лучевая колонна образован лучевым шиловидным отростком, ладьевидной фасеткой и прикреплениями лучеполулунной связки, лучеладьевидноголовчатой связкой и плечелучевой мышцы.
Лучевая колонна служит опорой для запястья при лучезапястном отклонении.
Связочные соединения лучезапястной и лучевых коллатеральных связок препятствуют смещению запястья [@rikli2007].
Компонент деформирующего усилия плечелучевой мышцы может воздействовать на лучевую колонну при травме и приводит к потере лучевой высоты (ЛВ[^5]) и наклон лучевой кости (НЛК[^6])
.

[^5]: ЛВ - лучевая высота

[^6]: НЛК - наклон лучевой кости

Промежуточная колонна является основным несущим компонентом модели с тремя колоннами, который необходимо оценивать на предмет конгруэнтности суставов и выравнивания механической оси запястья [@rikli2007].
Она образована полулунной фасеткой и сигмовидной выемкой.
Прикрепления связок к полулунной кости с ладонной стороны и трехглавой кости с дорсальной стороны обеспечивают важное ограничение поступательного движения запястья.
Связочные соединения между дистальным отделом лучевой кости и дистальным отделом локтевой кости важны для стабилизации предплечья.

Локтевая колонная служит осью вращения для проносупинации запястья [@rikli1996fractures].
Она состоит из дистального отдела локтевой кости и ТФХК, критически важного для стабильности дистального отдела лучезапястного сустава и вращения предплечья.
Биомеханические исследования показали, что потеря радиальной высоты всего на 5 мм может привести к значительному нарушению функции ТФХК [@adams1993].

## **1.2 Перелом дистального метаэпифиза лучевой кости**

### **1.2.1 Эпидемиология**

Перелом ДМЭ ЛК является одним из наиболее распространенных переломов среди костной патологии в целом [@jupiter1991fractures; @chung2001; @jerrhag2017].
Это ведущая причина посещения травматологических пунктов и неотложной помощи в мире, где на эту патологию приходится 17-20% всех диагностированных переломов [@court-brown2006; @wilcke2013].

Общая частота переломов ДМЭ ЛК варьируется в различных исследованиях по всему миру.
В Скандинавии этот показатель составляет около 30 на 10 000 в год, и почти 40% переломов приходится на детей в возрасте до 18 лет [@wilcke2013].

До сих пор нет единого мнения о наилучшем способе лечения перелома ДМЭ ЛК [@belloti2007; @okamura2018] и хотя хирургические методы и импланты постоянно развиваются, осложнения этого перелома сохраняются.
Неправильное сращение встречается достаточно часто, по различным данным до 33% случаев [@cole1966comminuted; @gaspar2017].

### **1.2.2 Структура тяжести получаемой травмы**

Что касается типа перелома в соответствии с классификацией АО, то в литературе указывается, что тип А является наиболее распространенным, а тип В - наименее распространенным [@koo2013; @brogren2007].
Однако Sander, A. L.
и коллеги отмечают в своем исследовании 2018 года [@sander2018] равную долю переломов типа А и С.
Учитывая, что процент тяжелых переломов увеличивался с интенсивностью травмы, разница отражает долю взрослых пациентов с высокоэнергитической травмой.
Интересно, что Dahlen H. C.
и коллеги в 2004 году исследовали переломы дистального отдела лучевой кости со смещением, классифицированные стандартными рентгенограммами как внесуставные переломы типа А2 и А3 по классификации АО, до оперативного лечения с помощью компьютерной томографии.
Сравнительный анализ неожиданно выявил вовлечение суставной поверхности дистального отдела лучевой кости в 57% случаев [@dahlen2004].
Из этого можно следует положение об ошибках определения типа перелома.

### **1.2.3 Инструментальная оценка повреждения**

*Рентгенологическая оценка*

Существует три основных рентгенологических измерения для оценки ДМЭ ЛК: ЛВ, НЛК и ладонный (ЛН) [@graham1997].
Следует также оценить смещение суставных поверхностей, сигмовидную выемку, конгруэнтность ДЛЛС и наличие перелома шиловидного отростка [@nana2005].

ЛВ — это расстояние между двумя линиями, проведенными перпендикулярно длинной оси лучевой кости в прямой проекции от вершины шиловидного отростка лучевой кости и уровня суставной поверхности локтевой кости.
Нормальная ЛВ находится в диапазоне 8-14 мм, значения варьируются от публикации к публикации [@lalone2015; @perugia2014].
Потеря ЛВ является показателем потери функции лучезапястного сустава.
Исправление укорочение лучевой кости является целью при хирургической тактике [@watson2016].

НЛК — это наклон дистальной поверхности лучевой кости по отношению к ее оси.
Угол радиального наклона определяется в прямой проекции как угол между линией, проведенной между точкой шиловидного отростка лучевой кости и самой медиальной точки суставной поверхности локтевой кости [@pope2014musculoskeletal].
НЛК менее 15° — это относительное показание к оперативному лечению перелома или деформации ДМЭ ЛК [@kehr2010david].
В норме этот показатель 21-25° (в среднем 22-24°) [@harisinghani2018primer; @guglielmi2001fundamentals].
При угле более 25° следует говорить о деформации Маделунга [@hanson2018].

ЛН является важным измерением при оценке переломов дистального отдела лучевой кости и деформаций лучевой кости.
ЛН оценивается на боковой рентгенограмме лучезапястного сустава, он соответствует углу, образованному линией, проведенной перпендикулярно оси лучевой кости, и линией, которая проходит через кончики тыльного и лучевого краев, т.е.
вдоль суставной поверхности лучевой кости) [@wolfe2021green; @graftiaux2015charles].
В норме этот показатель находится в диапазоне 7-15º [@perugia2014; @mignemi2013], в среднем 11º [@wolfe2021green; @graftiaux2015charles], хотя некоторые авторы считают нормальным диапазон 2-20º [@marincek2007emergency; @harisinghani2018primer].

*Роль компьютерной томографии*

Компьютерная томография (КТ[^7]) это важный инструмент для оценки поражения суставов.
Jeffrey Cole R.
и его коллеги в своем исследовании [@jeffreycole1997] сообщали об улучшении качества оценки конгруэнтности суставов по сравнению с обычной рентгенограммой.
Выявление вовлечения сустава является обязательным при оценке переломов ДМЭ ЛК с точки зрения оперативного планирования и прогностического показателя.
Исследование, подчеркивающее важность оценки состояния суставов, показало, что любая степень нарушения конгруэнтности суставов может привести к посттравматическому артрозу у 91% пациентов и у 100%, если они больше 2 мм [@knirk1986intra].
Визуализация поперечного сечения полезна, когда рисунок перелома неясен на обычных рентгенограммах [@arora2010].
Также было показано, что компьютерная томография улучшает выявление вовлечения скрытых переломов ладьевидной кости [@arora2010; @katz2001].

[^7]: КТ - компьютерная томография

Исследование Harness N. G.
и коллег [@harness2006] показало, что трехмерная визуализация в сочетании с двумерной визуализацией значительно изменили планы лечения, включая оперативный подход.
Компьютерную томографию с дополнительной лучевой нагрузкой и затратами не следует назначать при всех переломах дистального отдела лучевой кости, и использование компьютерной томографии в качестве дополнения лучше оставить на усмотрение лечащего хирурга.
[@bhandari2017].

### **1.2.4 Способы оценки функции при повреждении**

Стандартизированные результаты лечения пациентов позволяют проводить сравнение между различными медицинскими центрами.
Стандартизированный инструмент для оценки результатов лечения пациентов при переломах ДМЭ ЛК должен включать оценку боли, утвержденную шкалу результатов, о которых сообщают пациенты, показатели эффективности, рентгенограммы и оценку осложнений.
Следует скорректировать факторы, зависящие от конкретного пациента и травмы, которые изменяют результаты лечения [@hall2021].

**Самооценка пациентом функции** **запястья**

Самооценка пациентом функции запястья (СПФЗ[^8], от английского термина Patient-Rated Wrist Evaluation - PRWE) представляет собой анкету из 15 пунктов с подшкалами для измерения боли в запястье и недееспособности [@macdermid1998; @macdermid1996]

[^8]: СПФЗ - самооценка пациентом функции запястья от ангийского термина Patient-Rated Wrist Evaluation - PRWE

Многочисленные исследования показали, что СПФЗ является надежным, валидным и быстро реагирующим инструментом для измерения результатов перелома ДМЭ ЛК [@mehta2015; @kleinlugtenbelt2018]

СПФЗ предназначен для измерения результатов лечения заболеваний запястья, что делает его одним из наиболее часто используемых инструментов для измерения результатов перелома ДМЭ ЛК [@gupta2014measure; @macdermid1996]

Обширное исследование СПФЗ также включает установленную минимальную клинически значимую разницу (МКЗР[^9]) в 11,5 баллов.
Это важно особенно для переломов ДМЭ ЛК, что помогает исследователям определить клиническую значимость их результатов [@walenkamp2015a].

[^9]: МКЗР - минимальная клинически значимая разница

Наконец, СПФЗ коррелирует с другими хорошо зарекомендовавшими себя показателями результатов перелом ДМЭ ЛК, о которых сообщают пациенты, такими как\
анкета по нарушения функции кисти, предплечья и плеча[^10] (DASH - Disabilities of the Arm, Shoulder, and Hand Questionnaire), а также показатели боли по ВАШ[^11] [@paranaíba2017].

[^10]: DASH - Disabilities of the Arm, Shoulder, and Hand Questionnaire (анкета нарушения функции кисти, предплечья и плеча)

[^11]: ВАШ - визуальная аналоговая шкала

Основным ограничением СПФЗ является то, что его специфичность ограничивает возможность обобщения в отношении воздействия травмы на общее состояние здоровья человека [@macdermid2000].

**Анкета нарушения функции кисти, предплечья и плеча (DASH) и быстрый DASH**

DASH — это анкета, состоящая из 30 пунктов, которая измеряет функцию и симптомы заболеваний верхних конечностей [@hudak1996development].
Помимо стандартной оценки боли и функциональных возможностей, DASH включает дополнительные модули, оценивающие потенциал возвращения к работе, занятиям спортом и исполнительским искусством, так ким как изобразительное искусство или игра на музыкальных инструментах [@waljee2016].
Эта система была тщательно изучена и доказала свою валидность, надежность и отзывчивость для переломов и деформаций ДМЭ ЛК [@kleinlugtenbelt2018].
Это менее специфичный инструмент, чем СПФЗ, но между этими шкалами существует сильная корреляция [@macdermid2000].
В нескольких исследованиях была предпринята попытка установить минимальное клинически значимое различие по шкале DASH (5-15 баллов), но не существует минимального клинически значимого различия, специфичного для переломов ДМЭ ЛК [@franchignoni2014; @smith2016specificity].
Это может ограничить интерпретацию результатов клиницистами и исследователями [@tyser2014].

QuickDASH[^12] (быстрый DASH) — это сокращенный формат DASH, разработанный с использованием методов и целостности оригинальной анкеты.
[@beaton2005].
Заполнение более коротких анкет занимает меньше времени, что может повысить частоту ответов и качество данных [@ware2008].
Шкала QuickDASH сравнима с шкалой DASH с дополнительными преимуществами более короткого инструмента.
Аналогично шкале DASH, в исследованиях была предпринята попытка установить минимальное клинически значимое различие для шкалы QuickDASH (14-26 баллов), включая минимальное клинически значимое различие, характерное для переломов ДМЭ ЛК, получавших хирургическое лечение (26 пунктов) [@franchignoni2014; @smith2016specificity].

[^12]: QuickDASH - сокращенный формат DASH

**Michigan Hand Questionnaire and Brief Michigan Hand Questionnaire**

MHQ [^13] — это анкета, состоящая из 37 элементов, которая измеряет 6 аспектов для обеих верхних конечностей: боль, общую функцию кисти, повседневную деятельность, производительность труда, эстетику и удовлетворенность [@shauver2013].
Он уникален среди аналогичных инструментов для оценки результатов тем, что измеряет каждую руку отдельно [@waljee2016; @shauver2013].

[^13]: MHQ - **Michigan Hand Questionnaire,** Мичиганский опросник функции кисти.

Более того, это единственный инструмент для лечения верхних конечностей, учитывающий эстетические соображения [@shauver2013].

Его психометрические свойства хорошо зарекомендовали себя, отличаясь превосходной надежностью, валидностью, отзывчивостью и внутренней согласованностью [@shauver2013].

Хотя МКЗР для MHQ была установлена для других заболеваний верхних конечностей (8-23), попытка установить минимальную клинически значимую разницу для пациентов с переломами ДМЭ ЛК, получавших МОС[^14], была ограничена эффектом потолка, поскольку большинство пациентов возвращаются к нормальному высокому уровню функции к 3 месяцам после операции [@london2014].

[^14]: МОС - металл остеосинтез

По аналогии с QuickDASH была разработана сокращенная шкала Brief MHQ (bMHQ[^15]) [@waljee2011].
bMHQ охватывает те же 6 основных аспектов, что и MHQ, и является таким же валидным, надежным, отзывчивым, на его выполнение уходит примерно вполовину меньше времени [@waljee2011].
bMHQ отличается от MHQ тем, что он не различает латеральность, но это может быть менее актуально для переломов ДМЭ ЛК [@shauver2013; @waljee2011].
Как и в случае с MHQ, для переломов ДМЭ не был установлен МКЗР bMHQ.

[^15]: bMHQ - Brief Michigan Hand Questionnaire, короткий Мичиганский опросник функции кисти

**36-Item Short Form Health Survey**

SF-36[^16] — это анкета из 36 элементов, которая измеряет состояние здоровья в 8 областях: физическое функционирование, ролевое физическое функционирование, боль, общее здоровье, жизнеспособность, социальное функционирование, ролевое эмоциональное функционирование и психическое здоровье [@ware1992mos].
SF-36 также популярным методом измерения ранних результатов лечения переломов ДМЭ ЛК [@amadio1996].

[^16]: SF-36 - Short Form (36) Health Survey, краткая форма (36) о состоянии здоровья

По сравнению с результатами, полученными в зависимости от состояния верхних конечностей, SF-36 оценивает влияние травмы на общее состояние здоровья человека.
Такая перспектива полезна для того, чтобы оценить влияние травмы верхних конечностей на общее качество жизни.
Учитывая более широкую сферу применения инструмента, он менее чувствителен, чем его более специфические аналоги, такие как DASH и СПФЗ [@macdermid2000].
Тем не менее, его валидность и надежность хорошо подтверждены в литературе по результатам лечения, в частности, у пациентов с переломами ДМЭ ЛК [@jenkinson1994].

Краткий обзор состояния здоровья, состоящий из 12 пунктов (SF-12), представляет собой сокращенную версию, преимущества которой заключаются в том, что она более лаконична, хорошо согласуется с SF-36 и эффективна в популяции пациентов с переломами ДМЭ ЛК [@brogren2011].

**Информационная система измерения результатов, о которых сообщают пациенты**[^17] (PROMIS)

[^17]: **PROMIS - Patient-Reported Outcome Measurement Information System, Информационная система измерения результатов, о которых сообщают пациенты**

PROMIS была разработана Национальными институтами здравоохранения в качестве интегрированного инструмента для сбора информации о состоянии здоровья, о котором сообщают сами пациенты, в 3 основных областях: физическое, психическое и социальное здоровье [@cella2010].
В пределах этих трех доменов существуют поддомены, такие как физические функции и вмешательство в боль в области физического здоровья [@cella2010].

Банки элементов разрабатываются для каждого из этих поддоменов с использованием компьютерного адаптивного тестирования[^18] (КАТ).
КАТ использует теорию отклика элемента для оценки уровня функциональности и выбора подходящих элементов из банка для тестирования [@overbeek2015].
КАТ является его способность достигать большей точности при меньшем количестве вопросов [@overbeek2015].

[^18]: КАТ - компьютерное адаптивное тестирование

### **1.2.5 Неправильное сращение дистального метаэпифиза как результат лечения перелома**

НСП ДМЭ ЛК является наиболее частым осложнением этой травмы и, следовательно, относительно частым клиническим явлением.
Заболеваемость НСП ДМЭ ЛК, по-видимому, выше, когда перелом лечится иммобилизацией гипсовой повязкой, по данным литературы частота осложнения находится примерно около 24% [@katt2020; @sharma2014].
В то время как частота НСП ДМЭ ЛК ниже при оперативном лечении переломов [@sharma2014].
С появлением передовых хирургических методов частота НСП ДМЭ ЛК, по подсчетам, снизилась до 11% [@katt2020].
Margaliot Z.
и коллеги в 2005 году [@margaliot2005] провели мета-анализ результатов лечения наружной фиксации по сравнению с внутренней (пластинами и винтами) показал, что частота с применением внутренней НСП ДМЭ ЛК составляет около 4%.

Не все НСП ДМЭ ЛК являются симптоматическими.
Часто степень клинической тяжести не коррелирует с степенью костной деформацией.
Однако при симптомах НСП ДМЭ ЛК может привести к значительной инвалидности.
В недавнем долгосрочном последующем исследовании Ali и коллеги в 2018 году [@ali2018] пришли к выводу, что пациенты, перенесшие перелом дистального отдела лучевой кости в возрасте от 18 до 65 лет и у которых развился НСП ДМЭ ЛК, с большей вероятностью будут иметь неблагоприятные клинические исходы, включая ограничение активности и боль.
По сравнению с пациентами без НСП ДМЭ ЛК.
У пациентов с НСП ДМЭ ЛК показатели инвалидности руки, плеча и кисти были заметно хуже по сравнению с исходным уровнем в возрасте от 12 до 14 лет, разница, которая была клинически значимой.
Несмотря на субъективное несоответствие, не было объективных различий в отношении силы хвата или конечного диапазона движения.

## **1.3 Современные подход к лечению посттравматической деформации дистального метаэпифиза лучевой кости**

Переломы ДМЭ ЛК очень часто курируются консервативно с помощью техники закрытой ручной репозиции, в настоящее время хорошо известно, что такая тактика лечения связана с высокой частотой осложнений и частыми плохими результатами.
Посттравматическая деформация является наиболее распространенным осложнением [@mathews2015].

Неправильное сращение ДМЭ ЛК обычно возникает после консервативного лечения.
Примерно 25% переломов ДМЭ ЛК, пролеченных закрытыми способами, консолидируются с деформациями, которые превышают общие допустимые параметры [@miyake2011; @haase2012].

Однако и хирургическая фиксация переломов ДМЭ ЛК не лишена этой проблемы.
Когда стала более распространенной хирургическая тактика, можно увидеть увеличение доли этого осложнения в когорте прооперированных пациентов.
Независимо от используемого метода стабилизации, частота посттравматической деформации уменьшается только до 10% [@prommersberger2012; @schweizer2013].
В результате почти 80% деформации ДМЭ ЛК формируются после неудачной закрытой репозиции, а остальные 20% являются следствием остеосинтеза.
Как правило большая часть из этого числа — это процедуры, где выполняется минимально инвазивные методы, такие как черезкожные спицы Киршнера [@mckay2001; @delclaux2016].

### **1.3.1 Классификация деформации ДМЭ ЛК**

НСП ДМЭ ЛК может быть результатом внутрисуставного, внесуставного перелома, а также может быть комбинацией этих вариантов.
Среди наиболее распространённых характеристик деформации является сокращение ЛН в сагиттальной плоскости, потеря НЛК во фронтальной плоскости и сокращение ЛВ[@konul2011].
Кроме того, может существовать ротационная деформация дистального фрагмента относительно диафиза лучевой кости.
Prommersberger K.J.
и коллеги в 2004 году [@prommersberger2004] обнаружили ротационную деформацию у 23 из 37 пациентов с корригирующей остеотомией ДМЭ ЛК.

Как при дорсальной, так и при ладонной деформации были выявлены пронационные пространственные конфигурации, так и супинационные.
Хотя деформация в пронации относительно чаще встречалась у пациентов с ладонным наклоном деформации, статистически значимых различий между дорсальной и ладонной деформацией в отношении распределения направления ротационной деформации не было.
Недостаточность пронации-супинации не коррелировали с величиной ротационной деформации.
Кроме того, дистальный фрагмент может быть смещен либо в сагиттальной, либо во фронтальной плоскости [@mathew2013].
Внутрисуставные переломы ДМЭ ЛК разрешаются внутрисуставной ступенчатой деформацией, требующей специальные подходы к лечению [@delpiñal2017].

### **1.3.2 Жалобы пациентов с деформацией** ДМЭ ЛК

Следует сказать, что не все неанатомически консолидированные ДМЭ ЛК приводят к плохому функциональному исходу.
Однако многие пациенты с деформацией ДМЭ ЛК жалуются на уменьшение диапазона движений в лучезапястном суставе и снижение ротационных движений предплечья, слабость силы захвата и боль, особенно на локтевой стороне, где часто наблюдается компрессия локтевой кости в результате укорочения лучевой кости.

Многие пациенты, как женщины, так и мужчины, часто недовольны неприятным внешним видом запястья с выступающей головкой локтевой кости, типичной для переломов по типу Коллеса и Смита с посттравматической деформацией.
НСП ДМЭ ЛК может быть связано с синдромом запястного канала [@prommersberger2012; @gary2017].

### **1.3.3 Биомеханика дистального лучезапястного сустава при деформации**

Нормальная биомеханика запястья зависит от поддержания анатомического положения дистального конца лучевой кости относительно запястья и дистального конца локтевой кости.
Нормальное движение запястья состоит из сгибания и разгибания запястья более чем на 120°, отклонения запястья на 50° в радиальном и локтевом направлении и поворота предплечья на 150° в дистальном лучелоктевом суставе [@spies2020].
Дистальная лучевая кость несет 80% осевой нагрузки через запястье, а дистальная локтевая кость несет 20% [@onishi2016].
В клинических и лабораторных исследованиях разнонаправленная деформация ДМЭ ЛК приводила к изменениям лучезапястного сустава, срединно-пястного сустава и дистального лучезапястного сустава [@malone2014].

Костная деформация влияет на нормальную механику лучезапястного сустава, приводя к ограничению дуги разгибания--сгибания движения.
Кроме того, неправильное расположение влияет на нормальную передачу нагрузки не только через лучевую кость, но и через весь лучезапястный сустав с увеличением на локтевую кость.
Дорсальный наклон лучевой кости смещает осевую нагрузку через запястье дорсально и в локтевую кость и уменьшает площадь контакта сустава.
Распределение давления на лучевых суставных поверхностях становится более концентрированным [@katt2020; @meena2014] и может представлять собой предартритное состояние лучезапястного сустава [@prommersberger2012].

Кроме того, укорочение лучевой кости и дорсальный наклон суставной поверхности увеличивают усилие, переносимое локтевой костью.
Нагрузка через локтевую кость увеличивается с 21 до 67% от общей нагрузки по мере увеличения угла наклона дистального фрагмента лучевой кости с 10° наклона ладони до 45° дорсального наклона [@perugia2014].
Удлинение локтевой кости на 2,5 мм увеличивает усилие, переносимое локтевой костью, с 18,4 до 41,9% от общей осевой нагрузки [@tarallo2014].

Неправильное выравнивание поверхности дистального отдела лучевой кости как в сагиттальной, так и в фронтальной плоскостях может привести к снижению механического преимущества сухожилий сгибателей, когда они проходят через запястный канал [@prommersberger2012], уменьшая силу захвата.
Кроме того, в результате деформации дистального отдела лучевой кости также может возникнуть компрессионная невропатия срединного нерва [@pope2018; @dydyk2020median].

На уровне средней части запястья дорсальный наклон дистального отдела лучевой кости может привести к компенсаторной деформации сгибания в качестве адаптивной реакции на дорсально повернутый проксимальный ряд запястья [@fischer2013], внешнюю динамическую нестабильность средней части запястья [@niacaris2015] и фиксированное неправильное положение запястья при дорсальном сгибании [@fischer2013].

Угловая деформация и деформация с укорочением дистального отдела лучевой кости может привести к несоответствию дистального лучезапястного сустава и уменьшению площади лучезапястного контакта [@prommersberger2012].
Лучевой укорочение по отношению к дистальной части локтевой кости может увеличить напряжение в ТФХК [@dobbe2021] и привести к разрыву глубокой части дорсальной лучезапястной связки [@nypaver2021].
Эти факторы могут ограничивать дугу вращения предплечья [@ng2011]

McQueen M.
и Caspers J.
[@mcqueen1988] обнаружили, что движение было значительно хуже в запястьях с углом дорсального наклона более 12°.
Jenkins N., Mintowt-Czyz W.
[@jenkins1988mal], а также Cooney 3rd W.
и коллеги [@cooney1980complications] сообщили, что снижение силы захвата имеет тесную взаимосвязь с тяжестью остаточной деформации перелома.
Aro H. T.
и Koivunen T.
[@aro1991] обнаружили, что функциональный конечный результат был неудовлетворительным только у 4% пациентов с приемлемым анатомическим результатом, по сравнению с 25% пациентов с незначительным укорочением и 31% пациентов с грубым укорочением лучевой кости.

### **1.3.4 Рентгенологическая оценка**

Подробно о рентгенологической оценке описано в разделе "1.2.3 Инструментальная оценка повреждения".
Требуется рассчитать рентгенографические параметры НЛК, ЛВ и ЛН.
Как уже упоминалось, ротационную деформацию трудно оценить с помощью рентгенограмм в 2 плоскостях; при подозрении может быть полезна компьютерная томография.
Кроме того, конгруэнтность суставной поверхности и нарушения суставной поверхности также часто лучше визуализируются с помощью КИ.
Магнитно-резонансная томография (МРТ[^19]) может помочь выявить наличие повреждений мягких тканей, таких как разрывы межпальцевой связки и ТФХК [@cirpar2011rotational].

[^19]: Магнитно-резонансная томография

### **1.3.5 Показания и противопоказания к корригирующей остеотомии**

Абсолютных показаний к хирургическому вмешательству у пациентов с НСП ДМЭ ЛК не существует.
Необходимо учитывать степень нарушения и функциональные потребности каждого отдельного пациента.
Возраст, боль, слабость, нарушение функций и потеря подвижности должны учитываться при совместном принятии решений относительно необходимости хирургического вмешательства.
Например, у пожилых пациентов анатомическая деформация и функция могут не коррелировать напрямую.
Young BT и Rayan GM.
[@young2000] обнаружили, что пожилые, малоподвижные люди с плохими рентгенологическими показателями имели 88% удовлетворенности своими субъективными клиническими результатами.
Баллы были рассчитаны на основе конечного дорсального угла, потери радиальной длины и потери радиального наклона.
Аналогичным образом, Diaz-Garcia R.J.
и коллеги[@diaz-garcia2011] провели систематический обзор исходов и осложнений в отношении переломов дистального отдела лучевой кости у пациентов в возрасте старше 60 лет.
Обзор продемонстрировал худшие рентгенологические результаты у пациентов, получавших консервативное лечение.
Однако функциональные результаты ничем не отличались от результатов пациентов, получавших лечение различными хирургическими средствами.

### **1.3.6 Сроки проведения остеотомий**

Оптимальное время для вмешательства при НСП ДМЭ ЛК остается неясным в тех случаях, когда показано хирургическое вмешательство.
Jupiter J.B., Ring D.
[@jupiter1996] обнаружили, что результаты раннего (определяемого как менее чем через 14 недель после травмы) или позднего (более чем через 14 недель после травмы) деформация сопоставимы.
Однако сила захвата составила в среднем 42 кг после ранней реконструкции по сравнению с 25 кг после поздней реконструкции.
Авторы пришли к выводу, что у пациентов, которые соответствуют рентгенологическим критериям, предсказывающим функциональные ограничения, ранняя реконструкция технически проще, а общий период нетрудоспособности сокращается.
Другие рекомендуют хирургическое вмешательство, как только отмечается неправильное сращение, учитывая, что в течение 1-2 месяцев после травмы мозоль перелома может быть отделена от кортикальной кости, и анатомическое выравнивание может быть восстановлено более надежно [@haase2012].

### **1.3.7 Предоперационная подготовка**

Предоперационная подготовка включает точную оценку клинической ситуации и результатов рентгенологических исследований.
Показания к корректирующей остеотомии обычно основываются на простых рентгенограммах поврежденного лучезапястного сустава.
Сравнение противоположной стороны полезно для определения отклонения локтевой кости и наклона во фронтальной и сагиттальной плоскостях.
Компьютерная томография может быть полезна для выявления дегенеративных изменений и неправильного положения дистального лучезапястного сустава, а также ротационной деформации дистального отдела лучевой кости.
Артроскопия запястья может быть показана для оценки суставного хряща и связок, особенно при внутрисуставном неправильном сращении.

Важен предоперационный план хирургического вмешательства, показывающий уровень остеотомии, угол коррекции.
В настоящее время предоперационное планирование хирургического вмешательства часто осуществляется на компьютере [@kunz2013; @shintani2018].
Athwal и коллеги [@athwal2003] описали метод, который имеет дополнительное преимущество в снижении радиационного воздействия на пациента и хирургическую бригаду, поскольку рентгеноскопия не используется во время процедуры.
Другие преимущества метода с компьютерной поддержкой включают возможность выполнения нескольких хирургических симуляций для оптимизации плана выравнивания.

### **1.3.8 Оперативная техника**

#### 1.3.8.1 Неправильное сращение дистальных переломов лучевой кости с дорсальным углом

Наиболее часто встречаются переломы дистального отдела НСП ДМЭ ЛК с дорсальным углом.
Классически неправильное положение кости устранялось с дорсальной стороны в форме открытоуголной клиновидной остеотомии с использованием структурного костного трансплантата и остеосинтеза пластиной.
Преимуществом этого подхода является техническая простота при выполнении открытоугольной клиновидной остеотомии, а также механическое преимущество фиксации на стороне натяжения неправильного соединения дистальных переломов лучевой кости.

Vos D.I., Tiren D.
[@vos2014] в 2014 году провели лечение 11 пациентов (средний возраст 52 года, диапазон 18-71).
У всех пациентов были удовлетворительные результаты с точки зрения функции и боли.
Корригирующая остеотомия и стабилизация с помощью двухколонной фиксированной пластины без костного трансплантата обеспечивают достаточную стабильность.
У пациентов без факторов риска, предрасполагающих к несращению, эта процедура безопасна и осуществима.

Внедрение ладонных пластин с фиксированным углом сделало ладонный подход жизнеспособным вариантом для неправильного соединения дистальных переломов лучевой кости с дорсальным углом.
Это может быть достигнуто путем выполнения открытоугольной клиновидной остеотомии через стандартный или расширенный радиальный сгибатель запястья.
Хотя покрытие ладонный доступ имеет теоретическое преимущество в уменьшении осложнений, связанных с сухожилиями, с этими имплантатами могут возникнуть проблемы как с сухожилиями сгибателей, так и с сухожилиями разгибателей.
При наличии ладонного кортикального контакта костный трансплантат может не потребоваться [@haase2012; @ozer2011; @mahmoud2012], но существует потенциальный риск несращения и возможного отказа конструкции при раннем движении из-за зависимости от аппаратных средств для поддержки конструкции, если не используется структурный костный трансплантат [@mathews2015] Дистальная фиксация пластины перед остеотомией может обеспечить больший контроль, чем установка после выполнения разреза [@mahmoud2012].
При такой технике винты должны располагаться параллельно суставной поверхности.
Это также позволяет выполнять маневр подъема, когда пластина установлена дистально [@tarallo2013].

Если для выполнения разреза после установки дистального винта требуется улучшенная визуализация, винты можно удалить, оставив каналы на месте для замены пластины и винта непосредственно после остеотомии.

Также были описаны закрытоугольные клиновидные остеотомии для лечения неправильного соединения дистальных переломов лучевой кости под дорсальным углом.
Эти остеотомии предлагают потенциальное преимущество прямого контакта кости с костью и фиксации с компрессией через место остеотомии.

Posner и Ambrose [@posner1991] описали бипланарная закрытоугольную клиновидная остеотомия для коррекции ЛН так и НЛК.
Из-за увеличения отклонения локтевой кости после остеотомии процедура была сопряжена с резекцией головки локтевой кости.
Wada T.
и коллеги [@wada2011] сравнили остеотомию закрытоугольного клина с остеотомией открытоугольного клина, причем закрытоугольный клин обычно сочетался с укорочением локтевой кости.
Авторы не обнаружили никаких осложнений, связанных с дополнительной процедурой укорочения локтевой кости.
Кроме того, они обнаружили улучшения в восстановлении локтевой дисперсии, дуге разгибания-сгибания движения запястья и оценке запястья по сравнению с открытоугольной клиновидной остеотомией.

#### 1.3.8.2 Неправильное соединение с ладонным углом при переломах дистального отдела лучевой кости

Когда деформация возникает в результате увеличения угла наклона волоса, оптимальным подходом является открывающая клиновидная остеотомия, выполняемая со стороны волоса.
Sato et al [@sato2009] представили серию из 28 пациентов, которым была выполнена остеотомия для лечения ладонного неправильного соединения.
Всем пациентам был установлен структурный трансплантат гребня подвздошной кости и зафиксирован стандартными или фиксированными ладонной пластиной.
Все запястья срослись в месте остеотомии в среднем чуть более чем за 7 недель, а супинация улучшилась до 80 с 16 в среднем до операции.

#### 1.3.8.3 Внутрисуставное неправильное соединение переломов дистального отдела лучевой кости

Лечение неправильного соединения переломов дистального отдела лучевой кости с вовлечением суставов является сложной задачей и часто требует расширенной визуализации, такой как компьютерная томография, для получения точного определения костной деформации.

Ring D.
и коллеги [@ring2005] установили, что результаты лечения неправильного сращения переломов дистального отдела лучевой кости с помощью внутрисуставных и внесуставных остеотомий сопоставимы.
Остеотомия при неправильном сращении переломов дистального отдела лучевой кости может быть безопасно выполнена с помощью дорсального или ладонного доступа, может привести к улучшению функции и может ограничить необходимость в процедурах спасения в результате дегенеративных изменений запястья.
Может быть выполнена дорсальная капсулотомия, которая идеально подходит для пациентов с дорсальным подвывихом и неправильным сращением суставов при переломах дистального отдела лучевой кости в сагиттальной плоскости.
Использование остеотомии с помощью артроскопии было описано с хорошими результатами [@delpiñal2010; @delpiñal2006].

Piñal et al [@delpiñal2006] использовали компьютерную томографию для идентификации основных суставных фрагментов, а затем с помощью артроскопии фрагменты были идентифицированы с помощью зонда.
Затем в пространство сустава были введены остеотомии для мобилизации фрагментов под артроскопической визуализацией.
Затем фрагменты были уменьшены и зафиксированы с помощью ладонной пластины с фиксированным углом.
Авторы считали, что время для фиксации имеет важное значение, потому что через 3 месяца суставной хрящ может быть серьезно поврежден, и перестройка не принесет большой пользы в тот момент времени после травмы.
В последующем исследовании [@delpiñal2010], авторы обнаружили хорошие среднесрочные клинические и рентгенологические результаты у пациентов, получавших лечение с помощью этой методики.

#### 1.3.8.4 Костная пластика

Пустота, образовавшаяся при остеотомии открытоугольного клина, традиционно заполнялась аутогенным костным трансплантатом (структурным или неструктурным) или заменителем костного трансплантата.
Ring D.
и коллеги [@ring2002] показал сопоставимые результаты с неструктурным губчатым трансплантатом по сравнению со структурным трансплантатом гребня подвздошной кости у пациентов, получавших остеотомию ДМЭ ЛК.

Благодаря дополнительной прочности ладонных пластин с фиксированным углом для фиксации места остеотомии также использовались заменители костного трансплантата.
Luchetti R.
[@luchetti2004] сообщили об успешных результатах с использованием карбонизированного гидроксиапатита в диастазе после остеотомии, в то время как Yasuda M.
и коллеги [@yasuda2004] сообщил о зажившей остеотомии без потери фиксации костным цементом с фосфатом кальция.

Mahmoud M.
и коллеги [@mahmoud2012] сообщали об отличных результатах без заполнения трансплантатом при использовании фиксирующей ладонной пластины.
У 1 из 22 пациентов произошла небольшая потеря сокращения, которая не нуждалась в ревизионной операции.

Ozer K.
и коллеги [@ozer2011] установили, что до тех пор, пока сохранялся контакт с кортикальной областью лучевой кости, использование костного аллотрансплантата не улучшало конечный результат.
Считалось, что прочность конструкции, вызванная размещением дистальных винтов в зажившей кортикальной кости, была достаточной для обеспечения надлежащего заживления.

Mugnai, R.
и коллеги [@mugnai2016] в своем обзоре указывают, что в 7 из 12 рассмотренных исследований описывалось использование трансплантата; в остальных пяти исследованиях никакой трансплантат не использовался.
Тип неправильного соединения в большинстве исследований был дорсальным.
Время заживления было сопоставимым с использованием трансплантата или без него (в среднем 12,5 недели), в диапазоне от 7,5 до 16 недель.
Среднее улучшение показателей инвалидности руки, плеча и кисти составило 23 балла как в исследованиях, в которых использовался трансплантат, так и в тех, которые не использовали трансплантат.
Этот обзор продемонстрировал, что корригирующая остеотомия внесуставных переломов дистального отдела лучевой кости, обработанных фиксирующей ладонной пластиной, не обязательно требует костного трансплантата.

### **1.3.9 Осложнения**

Осложнения после корригирующей остеотомии ДМЭ ЛК такие же, как и после оперативного лечения острых переломов ДМЭ ЛК.
Одним из основных осложнений после корректирующей остеотомии является несращение.
Prommersberger K.J.
и коллеги в своем исследовании обнаружили 4 несращения из 400 остеотомий [@prommersberger2012].

Haghverdian J.C.
и коллеги [@haghverdian2019] сообщили об осложнениях корректирующих остеотомий при внесуставном неправильном соединении переломов дистального отдела лучевой кости.
Исследовательская группа состояла из 60 пациентов, которые проходили процедуру в течение 8 лет.
Частота осложнений составила почти 50%.
Были зарегистрированы инфекция, несращение, потеря сокращения, несостоятельность имплантата, повреждение нерва, повреждение сухожилия и сложный региональный болевой синдром, 20% из которых были связаны с сухожилиями.
Раздражение сухожилия и разрыв сухожилия были видны как при дорсальном, так и при ладонном доступе.
Частота осложнений была выше у пациентов, которым была проведена остеотомия дистракционного типа, по сравнению с теми, у кого остеотомия была связана с ладонным кортикальным слоем.
Rivlin M и коллегии [@rivlin2016] сообщили о 6 пациентах с разрывом разгибательной мышцы после остеотомии и фиксации ладонной пластины для неправильного соединения переломов дистального отдела лучевой кости.
Среднее время до разрыва сухожилия составляло 10 недель после операции.
Этиологические факторы разрывов включали образование дорсальной костной мозоли у 4 пациентов, выступание аппаратного обеспечения у одного и дорсальный остеофит у последнего пациента.

Неправильное сращение переломов дистального отдела лучевой кости остается наиболее распространенным осложнением нехирургического лечения переломов дистального отдела лучевой кости и представляет собой обычное клиническое явление.
Хирургическая коррекция - сложная проблема с непредсказуемыми клиническими исходами.
Профилактика неправильного сращения переломов дистального отдела лучевой кости - лучший способ действий.
Ладонной пластиной с фиксированным углом наклона, технология костного трансплантата, а также 3D-моделирование и компьютерные руководства по остеотомии являются многообещающими новыми технологиями, которые, вероятно, окажут положительное влияние на результаты хирургического лечения этой неприятной клинической проблемы.

# **1.4 Компьютерные технологии в процедурах корректирующей дистальной лучевой остеотомии**

Как уже говорилось, до 83% переломов дистального отдела лучевой кости с посттравматической деформацией являются симптоматическими: вызывающими боль, слабость или функциональные нарушения сустава [13,70].
[@prommersberger2012; @dy2014distal]

Эти симптоматические переломы ДМЭ ЛК с деформацией часто требуют хирургической коррекции для восстановления анатомии запястья и улучшения функциональных результатов.
Показания к хирургической коррекции преимущественно основаны на степени функциональных нарушений и рентгенологических данных, которые вызывают жалобы пациентов [@eygendaal2017; @slagel2007].

Функциональное воздействие деформации зависит от конкретного пациента, в зависимости от возраста, доминирования пораженной руки, уровня активности пациента и его требований [@hoare2017internal].

Тем не менее, приемлемые значения различаются у разных людей.
Часто незатронутое контралатеральное предплечье пациента используется в качестве ориентира для оценки целевых значений устранения деформации, однако вопрос использования коллатеральной стороны как области с целевыми значениями устранения коррекции требует уточнения [@gray2019; @dobbe2013].

Несколько исследований показали, что точная анатомическая реконструкция лучевой кости может улучшить функциональные результаты у пациентов с симптоматической деформацией [@prommersberger2012; @kunz2013].

Корригирующая остеотомия является методом выбора для восстановления анатомической конфигурации кости и оптимизации функциональных результатов [@dobbe2013].

Для того чтобы увеличить точность запланированной корригирующей остеотомии, необходимо тщательное предоперационное планирование.
Рентгенографическая оценка поврежденной конечности помогает получить подробную информацию о деформации и определить плоскость остеотомии, метод фиксации и, в некоторых случаях, необходимость формирования костного трансплантата [@prommersberger2012].

Традиционно предоперационное планирование основано на 2х рентгенограммах в переднее-задней и боковой проекциях [@dobbe2013; @dobbe2011; @vroemen2013].

Однако с помощью этого метода сложные деформации часто не устраняются [@vroemen2013; @miyake2012].

Особенно трудно оценить ротационные деформации на двумерных рентгенограммах [@prommersberger2012; @vroemen2013].

Компьютерные методы с трехмерными изображениями и моделями позволяют оценить пространственную конфигурацию деформации и могут потенциально улучшить функциональные и рентгенографические результаты корригирующих остеотомий [@miyake2011; @schweizer2013].

Планирование в виртуальной трехмерной среде включают три этапа [@schweizer2013].

Во-первых, данные собираются путем получения компьютерной томографии поврежденного и противоположного здорового предплечья, учетом того, что можно считать показатели коллатеральной стороны адекватными*.* Во-вторых, создаются виртуальные модели двух лучезапястных суставов.
Путем наложения деформированной лучевой кости на отзеркаленную версию здоровой стороны определяется пространственная конфигурация и степень деформации.
Затем в области неправильной консолидации выполняется виртуальная плоскость разреза, которая разделяет кость на проксимальную и дистальную части.
Дистальная и проксимальная части деформированной лучевой кости могут быть ротированы и переведены в соответствие с контралатеральной лучевой костью [@kunz2013].

На третьем и последнем этапе предоперационный план передается оперирующему хирургу для проведения самой операции [@murase2008].

Перенос запланированной остеотомии на реальную операцию - деликатная задача, для которой было предложено множество решений.
В своей простейшей форме виртуальные или физические 3D-модели помогают хирургу понять и визуализировать планируемую плоскость остеотомии [@walenkamp2015].

Кроме того, существует возможность корректировать смещение с помощью оптических устройств слежения [@croitoru2001], то есть компьютерной навигации.

Другим вариантом является использование синтетических шаблонов, которые могут быть помещены для остеотомии, тем самым восстанавливая исходное положение дистального отдела лучевой кости [@honigmann2016].

В конечном счете, методы 3D-планирования дают возможность создавать хирургические режущие направляющие и фиксирующие пластины для конкретного пациента [@schweizer2013; @dezillie2013; @streekstra2014].

Шаблоны изготавливаются в соответствии с анатомией пациентов и включают направляющие для сверления и одно или несколько отверстий для остеотомии.
Последовательно скорректированное положение может быть закреплено с помощью предварительно запланированных пластин, специфичных для конкретного пациента.
Достижения в области компьютерных технологий и средств 3D-печати сделали эти методы более доступными в повседневной клинической практике [@miyake2012].

### **1.4.1 Планирование в виртуальной среде**

### **1.4.2 Создание направляющего инструмента для конкретного пациента**

Streekstra G.
и коллеги [@streekstra2014] в 2014 году представили лечение перелома дистального отдела лучевой кости с тяжелым нарушением сращения с использованием индивидуальной пластины для точного пространственного позиционирования и фиксации.
Через двадцать месяцев после операции у пациента наблюдается почти безболезненная реконструкция и почти нормальный диапазон движений.

Honigmann, P. и коллеги [@honigmann2016] в 2016 году представили клинический случай.
54-летний мужчина получил внутрисуставной перелом ДМЭ ЛК рабочей правой стороны по АО-классификации 23 В3.
Перелом был прооперированы спицами Киршнера.
К тому времени, когда пациент повторно обратился, спицы Киршнера были удалены, и перелом прогрессировал до значимой посттравматической деформации.
Основными жалобами были ограниченное движение и боль в дистальном лучелоктевом суставе с пронацией и супинацией.
Рентгенограммы показали неправильное положение в лучелоктевом суставе из-за неправильного расположения дистальной лучевой кости с наклоном ладони 35 градусов и снижением высоты локтевой кости.
Для исправления неправильного положения была запланирована остеотомия открытым клином с использованием индивидуальный печатный шаблон для сверления.
Однако авторы преимуществанно описываю технику проведения операции, но не приводят результаты лечения.

Kunz, M.
[@kunz2013], в 2013 году метод компьютерной остеотомии дистального отдела лучевой кости, при котором для интраоперационного направителя используются печатные направляющие, адаптированные для конкретного пациента.
Операции были выполнены 8 пациентам, перенесшим остеотомию дистального отдела лучевой кости, со средним периодом наблюдения 7 месяцев (диапазон от 2 до 22 месяцев).
Среднее отклонение между достигнутым и запланированным радиальным наклоном в этих случаях составило 1,8° (SD, 0,8).
Для ладонного наклона среднее отклонение между запланированным и достигнутым углом составило 1,9° (SD, 1,5).
Среднее отклонение между достигнутым и запланированным отклонением локтевой кости составило 0,9 мм (SD, 1,1).
Послеоперационные осложнения включали один случай глубокой инфекции гребня подвздошной кости, который был успешно вылечен с помощью проведения хирургической обработки.
В одном случае полный артродез запястья был выполнен через 22 месяца после остеотомии дистального отдела лучевой кости из-за прогрессирующего посттравматического артрита.
Это осложнение было связано с сопутствующим повреждением суставной поверхности, а не с хирургическим лечением внесуставного неправильного соединения.

Miyake, J.
[@miyake2011] в 2011 году изучали клинически применимость виртуальных данных трехмерной остеотомии с использованием автоматизированного проектирования и технологий изготовления с использованием фиксирующих ладонных пластин при неправильном сращении ДМЭ ЛК.
Было пролечено 10 пациентов с деформацией метафизарной лучевой кости.
Корректирующая остеотомия была смоделирована с помощью трехмерных моделей, созданных с использованием данных компьютерной томографии.
Были смоделировали наиболее подходящие отверстия для проведения винтов, используя данные автоматизированного проектирования фиксирующей пластины.
Во время операции с помощью изготовленного на заказ хирургического шаблона были просверлены отверстия для винтов в соответствии с моделированием.
После остеотомии фиксация пластины с помощью предварительно просверленных отверстий для винтов позволила автоматически вправить дистальный лучевой фрагмент.
Аутогенная губчатая кость подвздошной кости была использована в качестве графта после фиксации пластины.
Среднее сгибание запястья улучшилось с 33 до операции до 60 после операции.
Среднее разгибание запястья составляло 70 до операции и 65 после операции.
Все пациенты испытывали боль в запястье до операции, которая исчезла или уменьшилась после операции.

Oka, K.
[@oka2008] в 2008 голу сообщили о случае неправильного внутрисуставного перелома дистального отдела лучевой кости, успешно вылеченного с помощью корректирующей остеотомии с помощью внесуставного подхода с использованием изготовленного на заказ хирургического руководства, разработанного на основе предоперационного трехмерного компьютерного моделирования.
Компьютерная томография показала смещение внутрисуставного фрагмента на 3 мм с дистальной миграцией.
Полное устранение ступеньки было достигнуто без артротомии, и послеоперационная рентгенограмма ясно показала, что несоответствие лучезапястного сустава было исправлено.
Гипсовая иммобилизация сохранялась в течение 3 недель после операции.
Пациент смог активно тренировать запястье и предплечье под наблюдением физиотерапевта, поскольку была достигнута хорошая фиксация между фрагментом и лучевой костью и предотвращена контрактура запястья после внутрисуставной остеотомии.
Через три месяца после операции было достигнуто сращивание костей, диапазон движений улучшился, и боль исчезла.
При окончательном наблюдении через 3 года после операции на рентгенограммах сохранялась конгруэнтность лучезапястного сустава, а на компьютерной томографии наблюдалась гладкая поверхность лучевого сустава.
Разгибание и сгибание запястья улучшились до 80° и 70° соответственно, а сила захвата увеличилась с 22 кг до операции до 45 кг после операции.
Кроме того, пациент больше не жаловался на какие-либо функциональные ограничения в повседневной жизни.

Rieger, M.
[@rieger2004] в 2004 году с октября 2002 по июнь 2003 прооперировали 11 с симптоматической посттравматической деформаций ДМЭ ЛК.
Все пациенты хорошо переносили хирургическую процедуру.
Во время операции хирургам-ортопедам ни в одном из случаев не требовалось изменять положение дистального отдела лучевой кости, которое определялось устройством для изменения положения.
При послеоперационном наблюдении было восстановлено анатомическое соотношение дистального отдела лучевой кости (НЛК 21,4°; ЛН 10,3°; ЛВ 0,5 мм).
Клинически было достигнуто значительное улучшение пронации (Р=0,012), супинации (Р=0,01), сгибания (Р=0,001) и разгибания (Р=0,006).
Боль уменьшилась с 54 до 7 баллов.

Schweizer, A.
[@schweizer2013] в 2013 году в своем исследовании индивидуальных направляющих на конкретного пациента при лечении НСП ДМЭ ЛК выявили, что это надежный метод коррекции внутрисуставных неправильных соединений дистального отдела лучевой кости.
Метод позволяет хирургу безопасно выполнять сложные внутрисуставные остеотомии и может помочь ограничить необходимость в восстановительных процедурах, таких как частичный или полный артродез запястья.

Dezillie M.
и коллеги [@dezillie2013] сообщают, что существует тенденция к достижению более высокой точности по мере накопления опыта, как со стороны хирурга, так и со стороны инженера-конструктора.
Авторы считают, что эта технология обладает потенциалом для достижения постоянной точности очень сложных коррекций.

Kunz et al [@kunz2013] описал методику трехмерного планирования и свой опыт у 9 пациентов с неправильным сращением дистального отдела лучевой кости со средним сроком наблюдения 7 месяцев.
Среднее отклонение между достигнутым и планируемым радиальным наклоном у этих пациентов составило 1,8 (SD, 0,8); для локтевого наклона - 1,9 (SD, 1,5); и для локтевого отклонения - 0,9 мм (SD, 1,1 мм).
Авторы выявили 2 осложнения: одну инфекцию и один случай посттравматического артроза, который потребовал артродеза запястья.

Schweizer et al [@schweizer2013] описали свой опыт с 6 пациентами с симптомами внутрисуставных аномалий дистального отдела лучевой кости, которым была проведена корригирующая остеотомия.
Остеотомии проводились с помощью 3D-печатных направляющих, и все они зажили через 2 месяца.
Через 1 год 4 пациента избавились от боли, у одного была легкая боль, а один испытывал умеренную боль во время тяжелой работы.
Движение запястья и сила захвата были улучшены у всех пациентов.
За 1 год наблюдения никаких дегенеративных изменений обнаружено не было [@katt2020].

Walenkamp, M. M. J.
[@walenkamp2015] и коллеги включили восемь пациентов в возрасте 13-64 лет, которым было проведено планирование в виртуальной среде корригирующей остеотомии остеотомия лучевой кости при посттравматической деформации.
Авторы оценили до и послеоперационное остаточное неправильное положение на 3D-реконструкциях, выраженное в шести параметрах позиционирования (три смещения вдоль и три поворота вокруг осей 3D-анатомической системы координат), и оценили послеоперационный диапазон движений запястья.
В этой небольшой серии случаев ладоннодорсальный наклон был значительно улучшен (р = 0,05).
Локтевой сдвиг, однако, увеличился при корректирующей остеотомии (6 из 8 случаев, 75 %).
Послеоперационная 3D-оценка выявила улучшение параметров позиционирования у пациентов при осевом вращательном выравнивании (62,5 %), радиальном наклоне (75 %), проксимодистальном смещении (83 %) и ладонноодорзальном смещении (88 %), хотя когорта была недостаточно большой, чтобы подтвердить это статистической значимостью.
У всех пациентов, кроме одного, улучшилась амплитуда движений (88 %).
Компьютерное 3D-планирование улучшает выравнивание лучевых неправильных соединений и улучшает функциональные результаты у пациентов с симптоматическим неправильным соединением лучевой кости.
Необходима дальнейшая разработка для улучшения переноса запланированного положения на интраоперационную кость.

Корректность позиционирования шаблона Caiti, G.
В.
[@caiti2017] в своем исследовании ошибка позиционирования индивидуальных направителей для остеотомии на различных участках лучевой кости определили, что точность позиционирования зависит от места установки и конструкции направляющей.
В дистальной и проксимальной радиальных областях точность направляющих с боковым расширением выше, чем у стандартных направляющих, и поэтому рекомендуется для дальнейшего использования.

Shintani K.
и коллеги считают [@shintani2018], что трехмерное планирование корригирующей остеотомии с использованием готового костного трансплантата достигла хороших результатов.
Все пациенты достигли хорошей консолидации на рентгенограмме при окончательном наблюдении.
Средние различия в ладонном наклоне, радиальном наклоне и лучелоктевом индексе между рабочей стороной и противоположной стороной составили 4,3°, 2,3° и 1,2 мм соответственно.
При окончательном наблюдении после операции показатели улучшились до отличных у 3 пациентов, хороших у 11 пациентов и удовлетворительных у 5 пациентов.
При окончательном наблюдении было два пациента с потерей коррекции, но ни один пациент не жаловался на боль

## **1.5 Резюме**

Посттравматическая деформация ДМЭ ЛК является часто встречающимся осложнением.
Неправильное сращение ДМЭ ЛК обычно возникает после консервативного лечения.
Примерно 25% переломов ДМЭ ЛК, пролеченных с использование закрытой ручной репозиции, консолидируются с деформациями, которые превышают общие допустимые пространственные параметры.

Для ДМЭ ЛК установлены допустимые пределы рентгенографической деформации [@dezillie2013; @dezillie2013].

Планирование в 3D корригирующей остеотомии значительно улучшает как рентгенологические, так и функциональные результаты у пациентов с неправильным переломом дистального отдела лучевой кости.
Во всех включенных исследованиях сообщалось об улучшении рентгенологических и/или функциональных параметров при значительном количестве осложнений.
К сожалению, в нашем исследовании не было выявлено исследований, сравнивающих результаты методов 3D-планирования с более традиционными методами планирования.
Более того, методы 3D-планирования могут быть полезны для более сложных случаев, что затрудняет реальное сравнение когорт.
Тем не менее, некоторые исследования показывают, что при обычных остеотомиях только 40% исправлений достигают в пределах 5° от запланированной коррекции угловой деформации (наклон ладони, радиальный наклон) и в пределах 2 мм от запланированного отклонения локтевой кости [@dezillie2013].

Другие исследования сообщают об относительно хороших результатах традиционных методов со значительным улучшением функции как внутрисуставных, так и внесуставных дефектов [@buijze2012].

Более того, вполне вероятно, что некоторые переломы выигрывают от 3D-запланированных процедур больше, чем другие.
Например, нарушения ротации трудно оценить и устранить с помощью традиционного планирования, и они коррелируют с клиническими последствиями [@vroemen2013].

Кроме того, внутрисуставные аномалии могут быть особенно полезны в результате процедуры, спланированной в 3D.
Суставные соединения часто требуют многоплоскостной остеотомии, которую может быть очень трудно выполнить при обычном планировании.
3D-планирование с инструкциями по сверлению и пиле для конкретного пациента может действительно облегчить эту сложную процедуру.
Большинство авторов подчеркивают важность 3D-планируемых корректирующих остеотомий с учетом того факта, что 3D-деформации часто не устраняются с помощью обычных методов 2D-планирования.
Vroemen J. C.
и его коллеги показали, что клинический исход коррелирует с 3D-дефицитом вращения, но не с 2D-параметрами оценки [@vroemen2013].

Впоследствии следует отметить, что в большинстве исследований в этом обзоре использовались традиционные рентгенограммы для оценки послеоперационного положения лучевой кости вместо метода визуализации, который облегчает 3D-оценку.
Остаточные деформации могли быть недооценены.

К недостаткам метода 3D-планирования относятся необходимость в специализированном программном обеспечении, время и усилия, необходимые для предоперационного планирования, облучение и затраты на изготовление шаблона на заказ и компьютерную томографию [@mulders2017].

Чтобы полностью понять дополнительную ценность 3D-планирования корректирующих остеотомий, мы считаем, что рандомизированное контролируемое исследование неизбежно.

Благодаря современным достижениям в области технологии 3D-печати большинство методов, рассмотренных в этом исследовании, становятся коммерчески доступными.
Несколько компаний (например, Xilloc BV, Маастрихт, Нидерланды или Materialise NV, Левен, Бельгия) предоставляют услуги по разработке руководств по разрезанию для конкретного пациента на основе данных CAT и данных лечащего хирурга.
Полный процесс виртуального планирования и производства имплантатов для конкретного пациента занимает 6-8 недель в зависимости от сложности случая.
Индивидуальные направляющие для резки и сверления, соответствующие геометрии костей пациентов, могут сделать менее доступные технологии, такие как оптические устройства слежения, устаревшими.
Учитывая важность точности, весьма вероятно, что будущие остеотомии будут идти рука об руку с методами 3D-планирования.

3D-планируемые корректирующие остеотомии показывают значительное улучшение как функциональных, так и рентгенологических результатов у пациентов с неправильным сращением дистального отдела лучевой кости.
С учетом современных достижений в области технологии 3D-печати это представляется многообещающим методом лечения сложных аномалий дистального отдела лучевой кости.
Однако необходимы дальнейшие исследования, чтобы сделать определенный вывод о клинической ценности методов 3D-планирования для посттравматической деформации ДМЭ ЛК, также требуется описание протокола создания шаблона-направителя, оценка использования коллатеральной стороны для использования параметров лучевого наклона.
ладонного наклона и лучелоктевого индекса

# Список литературы:
