@startuml
start
:Определены показания к операции;

group <b>Согласие на исследование </b>
:Пациент подписывает согласие на исследование;
#palegreen:<b>Регистрация данных:</b>
ФИО
Пол/Возраст
Рост/Вес/ИМТ
Оценка силы четырехглавой мышцы
Оценка объема движений
Заполнение шкалы Pain Catastrophizing Scale;
end group

group <b>Оперативный этап </b>
:оперативное вмешательство;
if (Рандомизация в группу) then (A)
:Протокол дексаметазона\n8 м/г;

else(B)

:Протокол дексаметазона\n0,3 мг/кг;
endif

#palegreen:<b>Регистрация данных:</b>
Время жгута
Время операции;
end group

group <b> 1 сутки после операции </b>
#palegreen:<b>Регистрация данных:</b>
Глюкоза (6 часов)
СРБ (12 часов)
Оценка ВАШ(6 часов)
Оценка ВАШ(12 часов)
Количество обезболивающих перпаратов;
end group

group <b> 2 сутки после операции </b>
#palegreen:<b>Регистрация данных:</b>
Глюкоза (24 часа)
СРБ (24 часа)
Оценка ВАШ(24 часа)
Количество обезболивающих перпаратов
Заполнение шкалы Pain Catastrophizing Scale
Заполнение шкалы Quality of Recovery-15;
end group

group <b> 3 сутки после операции </b>
#palegreen:<b>Регистрация данных:</b>
Количество обезболивающих перпаратов
Оценка ВАШ
Оценка силы четырехглавой мышцы
Оценка объема движений;

end group

group <b> 2-3 недели после операции </b>
#palegreen:<b>Регистрация данных:</b>
Длительность госпитализации
Осложнений по шкале Dindo-Clavien
Наличие инфекции;

end group

stop
@endumll